# SPDX-License-Identifier: GPL-3.0-or-later
"""ROS-free tests for mower_map.areas (run: python3 -m pytest src/mower_map/test)."""

import json
import math
import os

import numpy as np
import pytest

from mower_map import areas as core
from mower_map import import_vendor_geojson as cli

SQUARE = [(0.0, 0.0), (10.0, 0.0), (10.0, 10.0), (0.0, 10.0)]
HOLE = [(4.0, 4.0), (6.0, 4.0), (6.0, 6.0), (4.0, 6.0)]
# Optional: path to a vendor RobotData/map/<id>/map.geojson pulled off a mower (not in the repo).
VENDOR_SAMPLE = os.environ.get('MOWER_VENDOR_MAP_SAMPLE', '')


def _store():
    s = core.MapStore()
    s.add_area('lawn', SQUARE, False, [(HOLE, 'tree', core.SOURCE_USER)])
    return s


# ---------------------------------------------------------------- data model

def test_add_area_rejects_short_polygon():
    with pytest.raises(ValueError):
        core.MapStore().add_area('x', [(0, 0), (1, 1)])


def test_add_area_drops_closing_vertex_and_short_obstacles():
    s = core.MapStore()
    a = s.add_area('a', SQUARE + [SQUARE[0]], False, [([(0, 0), (1, 1)], '', 0)])
    assert len(a.polygon) == 4
    assert a.obstacles == []


def test_obstacle_ids_are_unique_and_nonzero():
    s = _store()
    s.add_area('b', SQUARE, False, [(HOLE, '', 0), ([(1, 1), (2, 1), (2, 2)], '', 0)])
    ids = [o.id for a in s.areas for o in a.obstacles]
    assert len(set(ids)) == 3 and 0 not in ids


def test_add_obstacle_dedup_and_navigation_rejected():
    s = _store()
    s.add_area('nav', SQUARE, True)
    ok, msg = s.add_obstacle(0, [(4.02, 4.0), (6.02, 4.0), (6.02, 6.0), (4.02, 6.0)])
    assert ok and 'duplicate' in msg and len(s.areas[0].obstacles) == 1
    ok, _ = s.add_obstacle(1, HOLE)
    assert not ok
    ok, _ = s.add_obstacle(7, HOLE)
    assert not ok


def test_pending_accept_and_discard():
    s = _store()
    s.add_obstacle(0, [(1, 1), (2, 1), (2, 2)], 'dig', core.SOURCE_DIG, pending=True)
    pid = s.areas[0].obstacles[-1].id
    assert s.discard_pending(pid)
    assert not s.discard_pending(pid)
    s.add_obstacle(0, [(1, 1), (2, 1), (2, 2)], 'dig', core.SOURCE_DIG, pending=True)
    pid = s.areas[0].obstacles[-1].id
    assert s.accept_pending(pid, 'hole') == 0
    assert s.areas[0].obstacles[-1].name == 'hole' and not s.areas[0].obstacles[-1].pending
    assert s.accept_pending(pid) is None


# ---------------------------------------------------------------- areas.dat

UPSTREAM_GOLDEN = (
    '# Mowgli ROS2 — Persisted areas and docking point\n'
    '# Auto-generated by map_server_node. Do not edit manually.\n\n'
    'datum_lat: 48.123456789\n'
    'datum_lon: 11.000000001\n\n'
    'area_count: 2\n\n'
    'area_0_name: lawn\n'
    'area_0_polygon: 0,0;10,0;10,10;0,10\n'
    'area_0_is_navigation: 0\n'
    'area_0_obstacle_count: 2\n'
    'area_0_obstacle_0: 4,4;6,4;6,6;4,6\n'
    'area_0_obstacle_0_name: tree\n'
    'area_0_obstacle_1: 1,1;2,1;2,2\n'
    'area_0_obstacle_1_source: 1\n'
    '\n'
    'area_1_name: path\n'
    'area_1_polygon: -1.5,0.333333;2.595,-0.12;12345.7,0.1\n'
    'area_1_is_navigation: 1\n'
    'area_1_obstacle_count: 0\n'
    '\n')


def _golden_store():
    s = _store()
    s.add_obstacle(0, [(1, 1), (2, 1), (2, 2)], '', core.SOURCE_TRACKER)
    s.add_obstacle(0, [(8, 8), (9, 8), (9, 9)], 'dig', core.SOURCE_DIG, pending=True)
    s.add_area('path', [(-1.5, 1 / 3), (2.5949999999999998, -0.12), (12345.6789, 0.1)], True)
    return s


def test_format_matches_upstream_byte_for_byte():
    text = core.format_areas_dat(_golden_store().areas, 48.123456789, 11.000000001)
    assert text == UPSTREAM_GOLDEN


def test_no_datum_stamp_when_unset():
    text = core.format_areas_dat(_store().areas)
    assert 'datum_lat' not in text
    assert text.startswith('# Mowgli ROS2')
    assert '\n\narea_count: 1\n\n' in text


def test_parse_golden():
    areas, datum = core.parse_areas_dat(UPSTREAM_GOLDEN)
    assert datum == pytest.approx((48.123456789, 11.000000001))
    assert [a.name for a in areas] == ['lawn', 'path']
    assert areas[1].is_navigation and not areas[0].is_navigation
    assert areas[0].obstacles[0].name == 'tree'
    assert areas[0].obstacles[1].source == core.SOURCE_TRACKER
    assert areas[1].polygon[2][0] == pytest.approx(12345.7, abs=0.01)


def test_round_trip_is_stable(tmp_path):
    p = str(tmp_path / 'sub' / 'areas.dat')
    core.save_areas_file(p, _golden_store().areas, 48.123456789, 11.000000001)
    areas, _ = core.load_areas_file(p)
    s = core.MapStore()
    s.load(areas)
    assert core.format_areas_dat(s.areas, 48.123456789, 11.000000001) == UPSTREAM_GOLDEN


def test_pending_obstacles_not_persisted():
    text = core.format_areas_dat(_golden_store().areas)
    assert 'dig' not in text and 'area_0_obstacle_count: 2' in text


def test_parser_tolerates_legacy_and_bad_entries():
    text = ('# comment\nno colon here\ndock_x: 5\ndock_qw: 1\narea_count: 3\n'
            'area_0_name: a: with colon\narea_0_polygon: 0,0;1,0;1,1\n'
            'area_0_obstacle_count: 3\n'
            'area_0_obstacle_0: 0.1,0.1;0.2,0.1;0.2,0.2\n'
            'area_0_obstacle_1: 0.1,0.1;0.2,0.1;0.2,0.2\n'
            'area_0_obstacle_2: 0,0;1,1\n'
            'area_1_name: degenerate\narea_1_polygon: 0,0;1,1\n'
            'area_2_name: c\narea_2_polygon: 0,0;2,0;garbage;2,2\n')
    areas, datum = core.parse_areas_dat(text)
    assert datum is None
    assert [a.name for a in areas] == ['a: with colon', 'c']
    assert len(areas[0].obstacles) == 1          # dup + short dropped
    assert len(areas[1].polygon) == 3            # garbage point skipped


def test_dock_yaml_round_trip(tmp_path):
    d = core.DockPose(1.5, -2.25, 0.5, [(0.2, 0.275), (0.2, -0.275), (-0.2, -0.275)])
    p = str(tmp_path / 'dock_pose.yaml')
    core.save_dock_file(p, d)
    back = core.load_dock_file(p)
    assert (back.x, back.y, back.yaw) == pytest.approx((1.5, -2.25, 0.5))
    assert np.allclose(back.outline, d.outline, atol=1e-6)


def test_robot_yaml_splice_preserves_layout(tmp_path):
    p = tmp_path / 'mowgli_robot.yaml'
    p.write_text('mowgli:\n  ros__parameters:\n    datum_lat: 1.0\n'
                 '    dock_pose_x: 0.0   # comment kept\n    dock_pose_y: 0.0\n'
                 '    dock_pose_yaw: 0.0\n')
    assert core.update_robot_yaml_dock_pose(str(p), 1.25, -3.0, 1.5707963)
    text = p.read_text()
    assert '    dock_pose_x: 1.250000   # comment kept\n' in text
    assert 'dock_pose_y: -3.000000' in text and 'dock_pose_yaw: 1.570796' in text
    assert 'datum_lat: 1.0' in text
    d = core.read_robot_yaml_dock_pose(str(p))
    assert (d.x, d.y, d.yaw) == pytest.approx((1.25, -3.0, 1.570796))
    assert not core.update_robot_yaml_dock_pose(str(tmp_path / 'missing.yaml'), 0, 0, 0)


# ---------------------------------------------------------------- geometry

def test_points_in_polygon_and_distance():
    xs = np.array([5.0, -1.0, 10.5, 9.99])
    ys = np.array([5.0, 5.0, 5.0, 9.99])
    assert core.points_in_polygon(xs, ys, SQUARE).tolist() == [True, False, False, True]
    d = core.distance_to_polygon_edges(xs, ys, SQUARE)
    assert d == pytest.approx([5.0, 1.0, 0.5, 0.01])


def test_grid_snapping_and_size_guard():
    spec = core.grid_for_polygons([SQUARE], 0.1, 2.0)
    assert (spec.origin_x, spec.origin_y) == pytest.approx((-2.0, -2.0))
    assert (spec.width, spec.height) == (140, 140)
    with pytest.raises(ValueError):
        core.grid_for_polygons([[(0, 0), (1e5, 0), (1e5, 1e5)]], 0.1, 0.0)
    empty = core.grid_for_polygons([], 0.1, 2.0)
    assert empty.width == 100 and empty.origin_x == pytest.approx(-5.0)


def _cell(spec, mask, x, y):
    r, c = spec.index_of(x, y)
    return int(mask[r, c])


def test_keepout_mask_values():
    s = _store()
    s.add_area('nav', [(10.0, 4.0), (14.0, 4.0), (14.0, 6.0), (10.0, 6.0)], True)
    dock = core.DockPose(13.0, 5.0, 0.0, [(0.2, 0.3), (0.2, -0.3), (-0.2, -0.3), (-0.2, 0.3)])
    spec = core.grid_for_polygons([a.polygon for a in s.areas], 0.1, 2.0)
    mask = core.build_keepout_mask(s.areas, spec, dock.outline_in_map())
    assert mask.dtype == np.int8 and mask.shape == (spec.height, spec.width)
    assert _cell(spec, mask, 2.0, 2.0) == 0        # mowing area
    assert _cell(spec, mask, 5.0, 5.0) == 100      # obstacle
    assert _cell(spec, mask, 11.0, 5.0) == 0       # navigation area
    assert _cell(spec, mask, 13.0, 5.0) == 100     # dock outline
    assert _cell(spec, mask, -1.0, -1.0) == 100    # outside everything
    assert _cell(spec, mask, 12.0, 8.0) == 100


def test_keepout_obstacle_margin_and_non_lethal_outside():
    s = _store()
    spec = core.grid_for_polygons([SQUARE], 0.1, 1.0)
    mask = core.build_keepout_mask(s.areas, spec, None, obstacle_margin=0.3)
    assert _cell(spec, mask, 3.85, 5.0) == 100 and _cell(spec, mask, 3.55, 5.0) == 0
    free_outside = core.build_keepout_mask(s.areas, spec, None, lethal_outside_areas=False)
    assert _cell(spec, free_outside, -0.5, -0.5) == 0


def test_empty_map_mask_is_free():
    spec = core.grid_for_polygons([], 0.1, 2.0)
    mask = core.build_keepout_mask([], spec, None)
    assert int(mask.max()) == 0


def test_progress_stamp_and_resize():
    spec = core.grid_for_polygons([SQUARE], 0.1, 0.0)
    g = core.ProgressGrid(spec)
    n = g.stamp_disc(5.0, 5.0, 0.15)
    assert n == int(np.count_nonzero(g.data == 100)) and 4 <= n <= 12
    assert g.stamp_disc(5.0, 5.0, 0.15) == 0           # already stamped
    assert g.stamp_disc(50.0, 50.0, 0.15) == 0         # off-grid is harmless
    bigger = core.grid_for_polygons([SQUARE], 0.1, 3.0)
    g.resize(bigger)
    assert g.data.shape == (bigger.height, bigger.width)
    assert int(np.count_nonzero(g.data == 100)) == n
    r, c = bigger.index_of(5.0, 5.0)
    assert g.data[r, c] == 100
    g.reset()
    assert int(g.data.max()) == 0


def test_boundary_classifier_debounce_and_lethal():
    areas = _store().areas
    bc = core.BoundaryClassifier(soft_margin=0.0, lethal_margin=0.5, debounce_samples=3)
    assert bc.update(*core.robot_area_status(5, 5, areas)) == (False, False)
    out = core.robot_area_status(10.2, 5, areas)
    assert out == (False, pytest.approx(0.2))
    assert bc.update(*out) == (False, False)
    assert bc.update(*out) == (False, False)
    assert bc.update(*out) == (True, False)
    assert bc.update(*core.robot_area_status(11.0, 5, areas)) == (True, True)
    assert bc.update(*core.robot_area_status(5, 5, areas)) == (False, False)


def test_recovery_point():
    areas = _store().areas
    r = core.recovery_point(12.0, 5.0, areas, offset=0.8)
    assert r['success'] and r['distance_outside'] == pytest.approx(2.0)
    assert (r['x'], r['y']) == pytest.approx((9.2, 5.0))
    assert r['yaw'] == pytest.approx(math.pi)
    assert not core.recovery_point(5, 5, areas)['success']
    assert core.recovery_point(5, 5, [])['message'] == 'no areas defined'


def test_yaw_std():
    assert core.yaw_circular_std([0.1] * 20) == pytest.approx(0.0, abs=1e-6)
    assert core.yaw_circular_std([math.pi - 0.001, -math.pi + 0.001] * 10) < 0.01
    assert core.yaw_circular_std([0.0, 0.5]) > 0.2
    assert core.yaw_from_quaternion(0, 0, math.sin(0.4), math.cos(0.4)) == pytest.approx(0.8)


# ---------------------------------------------------------------- importer

def _vendor_doc():
    ring = [[0.8, -1.0, 0.1, 0, 0, 1], [6.0, -1.0, 0, 0, 0, 1], [6.0, 3.0, 0, 0, 0, 1],
            [0.8, 3.0, 0, 0, 0, 1], [0.8, -1.0, 0.1, 0, 0, 1]]
    f = lambda t, geom, coords, **p: {  # noqa: E731
        'type': 'Feature', 'geometry': {'type': geom, 'coordinates': coords},
        'properties': dict(dict(id='id%d_%d' % (t, len(p)), name='', parent_id=0, type=t), **p)}
    return {'type': 'FeatureCollection', 'features': [
        f(3, 'LineString', [[0, 0, 0, 0, 0, 1], [0.8, 0, 0, 0, 0, 1]], name='A'),
        f(1, 'Polygon', [ring], name='A', id='area-a'),
        f(4, 'Polygon', [[[2, 0], [3, 0], [3, 1], [2, 1]]], parent_id='area-a', id='o1'),
        f(4, 'Polygon', [[[4, 0], [5, 0], [5, 1], [4, 1]]], parent_id='', id='o2'),
        f(4, 'Polygon', [[[5.5, 2.5], [7, 2.5], [7, 4], [5.5, 4]]], parent_id='', id='o3'),
        f(4, 'Polygon', [[[20, 20], [21, 20], [21, 21]]], parent_id='', id='o4'),
        f(4, 'Polygon', [[[-0.3, -0.75], [-0.3, 0.75], [1.7, 0.75], [1.7, -0.75]]],
          parent_id='', id='dockzone'),
        f(5, 'Polygon', [[[0.2, 0.275], [0.2, -0.275], [-0.2, -0.275], [-0.2, 0.275]]]),
        f(6, 'Point', [0, 0, 0.1, 0.1, 0], name='charge_point'),
        f(7, 'Point', [0.8, 0], name='undock_point'),
        f(8, 'Point', [0, 0, 0.1, 0.1]),
    ]}


def test_import_vendor_areas_obstacles_dock():
    res = core.import_vendor_geojson(_vendor_doc())
    mow = [a for a in res.areas if not a.is_navigation]
    nav = [a for a in res.areas if a.is_navigation]
    assert len(mow) == 1 and mow[0].name == 'A' and len(mow[0].polygon) == 4
    assert mow[0].polygon[0] == (0.8, -1.0)                  # x,y only
    # o1 by parent_id, o2 by centroid containment, o3 by overlap; o4 and dock zone dropped
    assert len(mow[0].obstacles) == 3
    assert any('outside every area' in w for w in res.warnings)
    assert any('dock no-mow zone' in w for w in res.warnings)
    assert len(nav) == 1 and nav[0].name == 'channel A'
    assert core.point_in_polygon(0.0, 0.0, nav[0].polygon)    # dock covered by the channel
    assert nav[0].channel == [(0.0, 0.0), (0.8, 0.0)]         # centreline kept (re-editable)
    assert nav[0].channel_width_m == pytest.approx(0.7)
    assert (res.dock.x, res.dock.y, res.dock.yaw) == pytest.approx((0, 0, 0))
    assert len(res.dock.outline) == 4


def test_import_dock_yaw_and_outline_local_frame():
    doc = _vendor_doc()
    for feat in doc['features']:
        t = feat['properties']['type']
        if t == 6:
            feat['geometry']['coordinates'] = [1.0, 1.0]
        if t == 7:
            feat['geometry']['coordinates'] = [1.0, 2.0]
        if t == 5:
            feat['geometry']['coordinates'] = [[[1.0, 1.5], [0.5, 1.5], [0.5, 0.5]]]
    res = core.import_vendor_geojson(doc, import_channels=False, keep_dock_zone_obstacles=True)
    assert res.dock.yaw == pytest.approx(math.pi / 2)
    assert np.allclose(res.dock.outline_in_map(), [(1.0, 1.5), (0.5, 1.5), (0.5, 0.5)])
    assert all(not a.is_navigation for a in res.areas)


def test_buffer_polyline():
    poly = core.buffer_polyline([(0, 0), (2, 0)], 0.5)
    assert core.polygon_area(poly) == pytest.approx(3.0 * 1.0)
    bent = core.buffer_polyline([(0, 0), (2, 0), (2, 2)], 0.3)
    for pt in [(-0.25, 0), (1, 0.2), (2, 1), (2.25, 2.25)]:
        assert core.point_in_polygon(pt[0], pt[1], bent)
    assert not core.point_in_polygon(1, 1, bent)


def test_cli_writes_files(tmp_path, capsys):
    src = tmp_path / 'map.geojson'
    src.write_text(json.dumps(_vendor_doc()))
    robot = tmp_path / 'mowgli_robot.yaml'
    robot.write_text('mowgli:\n  ros__parameters:\n    dock_pose_x: 9.0\n'
                     '    dock_pose_y: 9.0\n    dock_pose_yaw: 9.0\n')
    out = tmp_path / 'maps' / 'areas.dat'
    assert cli.main([str(src), '--out', str(out), '--robot-yaml', str(robot)]) == 0
    areas, _ = core.load_areas_file(str(out))
    assert len(areas) == 2
    assert core.load_dock_file(str(tmp_path / 'maps' / 'dock_pose.yaml')).outline
    assert 'dock_pose_x: 0.000000' in robot.read_text()


@pytest.mark.skipif(not os.path.isfile(VENDOR_SAMPLE),
                    reason='set MOWER_VENDOR_MAP_SAMPLE to a vendor map.geojson')
def test_import_live_vendor_sample():
    res = core.import_vendor_geojson_file(VENDOR_SAMPLE)
    mow = [a for a in res.areas if not a.is_navigation]
    assert len(mow) == 1 and len(mow[0].polygon) >= 50
    assert res.dock.yaw == pytest.approx(0.0)
    areas, _ = core.parse_areas_dat(core.format_areas_dat(res.areas))
    assert len(areas) == len(res.areas)


# ---------------------------------------------------------------- nav mask

def _cell(spec, mask, x, y):
    r, c = spec.index_of(x, y)
    return int(mask[r, c])


def test_nav_mask_dilates_areas_and_ignores_dock():
    s = _store()
    spec = core.grid_for_polygons([SQUARE], 0.1, 2.0)
    dock = [(-0.2, 0.275), (0.2, 0.275), (0.2, -0.275), (-0.2, -0.275)]
    mowing = core.build_keepout_mask(s.areas, spec, dock, 0.0, True)
    nav = core.build_nav_mask(s.areas, spec, nav_margin=0.35, obstacle_margin=0.10)
    # dock at the area corner: lethal for mowing, free for navigation
    assert _cell(spec, mowing, 0.05, 0.05) == core.LETHAL
    assert _cell(spec, nav, 0.05, 0.05) == core.FREE
    # just outside the boundary: lethal for mowing, free within nav_margin
    assert _cell(spec, mowing, -0.25, 5.0) == core.LETHAL
    assert _cell(spec, nav, -0.25, 5.0) == core.FREE
    assert _cell(spec, nav, -0.55, 5.0) == core.LETHAL
    # dock approach pose 0.8 m in front of a dock on the boundary, pointing out
    assert _cell(spec, nav, 5.0, -0.25) == core.FREE
    # obstacles grown by obstacle_margin
    assert _cell(spec, nav, 5.0, 5.0) == core.LETHAL
    assert _cell(spec, nav, 3.95, 5.0) == core.LETHAL
    assert _cell(spec, nav, 3.75, 5.0) == core.FREE
    assert (nav == core.FREE).sum() > (mowing == core.FREE).sum()


def test_nav_mask_ring_footprint_clear():
    """A robot centre 0.09 m inside the boundary keeps its 0.27 m half width
    on free cells."""
    s = _store()
    spec = core.grid_for_polygons([SQUARE], 0.1, 2.0)
    nav = core.build_nav_mask(s.areas, spec)
    for dx in np.arange(-0.27, 0.28, 0.05):
        assert _cell(spec, nav, 0.09 + dx, 2.0) == core.FREE


def test_nav_mask_no_areas_is_free():
    spec = core.grid_for_polygons([], 0.1, 2.0)
    assert (core.build_nav_mask([], spec) == core.FREE).all()


# ---------------------------------------------------------------- dock corridor

def _far_dock_case(area_x0=2.5):
    """Dock at (0,0) yaw 0, approach (0.8,0); lawn starts at x=area_x0."""
    s = core.MapStore()
    s.add_area('lawn', [(area_x0, -3.0), (area_x0 + 6.0, -3.0),
                        (area_x0 + 6.0, 3.0), (area_x0, 3.0)])
    dock = core.DockPose(0.0, 0.0, 0.0)
    return s, dock


def test_dock_corridor_frees_dock_approach_and_gap():
    s, dock = _far_dock_case(2.5)
    corridor = core.dock_corridor(dock, s.areas, 0.8, 0.35, 5.0)
    assert corridor.connected and corridor.gap_m == pytest.approx(1.7)
    assert corridor.path[-1] == pytest.approx((2.5, 0.0))
    polys = [a.polygon for a in s.areas] + [corridor.polygon()]
    spec = core.grid_for_polygons(polys, 0.1, 2.0)
    without = core.build_nav_mask(s.areas, spec, 0.35, 0.10)
    nav = core.build_nav_mask(s.areas, spec, 0.35, 0.10, corridor)
    for x, y in ((0.0, 0.0), (0.8, 0.0), (1.6, 0.0), (0.05, 0.25)):
        assert _cell(spec, without, x, y) == core.LETHAL
        assert _cell(spec, nav, x, y) == core.FREE
    assert _cell(spec, nav, 1.6, 0.6) == core.LETHAL      # outside the half width
    assert _cell(spec, nav, -0.6, 0.0) == core.LETHAL     # behind the dock
    # the published outline covers the same points
    poly = corridor.polygon()
    for q in ((0.0, 0.0), (0.8, 0.0), (1.6, 0.0)):
        assert core.point_in_polygon(*q, poly)
    assert not core.point_in_polygon(1.6, 0.6, poly)


def test_dock_corridor_capped():
    s, dock = _far_dock_case(10.0)
    corridor = core.dock_corridor(dock, s.areas, 0.8, 0.35, 5.0)
    assert not corridor.connected and corridor.gap_m == pytest.approx(9.2)
    assert corridor.path == [(0.0, 0.0), pytest.approx((0.8, 0.0))]
    spec = core.grid_for_polygons([a.polygon for a in s.areas] + [corridor.polygon()], 0.1, 2.0)
    nav = core.build_nav_mask(s.areas, spec, 0.35, 0.10, corridor)
    assert _cell(spec, nav, 0.0, 0.0) == core.FREE
    assert _cell(spec, nav, 0.8, 0.0) == core.FREE
    assert _cell(spec, nav, 5.0, 0.0) == core.LETHAL


def test_dock_corridor_approach_inside_area():
    s, dock = _far_dock_case(0.5)
    corridor = core.dock_corridor(dock, s.areas, 0.8, 0.35, 5.0)
    assert corridor.connected and corridor.gap_m == 0.0 and len(corridor.path) == 2


def test_dock_corridor_mowing_mask_unchanged_and_obstacles_win():
    s, dock = _far_dock_case(2.5)
    s.add_obstacle(0, [(1.5, -0.1), (1.7, -0.1), (1.7, 0.1), (1.5, 0.1)], 'rock')
    corridor = core.dock_corridor(dock, s.areas, 0.8, 0.35, 5.0)
    spec = core.grid_for_polygons([a.polygon for a in s.areas] + [corridor.polygon()], 0.1, 2.0)
    outline = [(-0.2, 0.275), (0.2, 0.275), (0.2, -0.275), (-0.2, -0.275)]
    m1 = core.build_keepout_mask(s.areas, spec, outline, 0.0, True)
    nav = core.build_nav_mask(s.areas, spec, 0.35, 0.10, corridor)
    m2 = core.build_keepout_mask(s.areas, spec, outline, 0.0, True)
    assert np.array_equal(m1, m2)
    assert _cell(spec, m1, 0.0, 0.0) == core.LETHAL
    assert _cell(spec, m1, 1.0, 0.0) == core.LETHAL
    assert _cell(spec, nav, 1.6, 0.0) == core.LETHAL      # obstacle inside the corridor


def test_dock_corridor_none_without_dock():
    assert core.dock_corridor(None, [], 0.8) is None


def test_dock_measured_flag_round_trip(tmp_path):
    p = str(tmp_path / 'dock_pose.yaml')
    core.save_dock_file(p, core.DockPose(1.0, 2.0, 0.5, None, measured=True))
    assert 'dock_pose_measured: true' in open(p).read()
    assert core.load_dock_file(p).measured is True
    core.save_dock_file(p, core.DockPose(1.0, 2.0, 0.5))
    assert 'dock_pose_measured' not in open(p).read()
    assert core.load_dock_file(p).measured is False


def test_placeholder_dock_file_is_not_measured():
    # the file on the mower before calibration (written by an earlier map_server)
    text = ('dock_pose_x: 0.000000\ndock_pose_y: 0.000000\ndock_pose_yaw: 0.000000\n'
            'dock_outline: "0.2,0.275;0.2,-0.275;-0.2,-0.275;-0.2,0.275"\n')
    d = core.parse_dock_yaml(text)
    assert d is not None and d.measured is False
    assert core.parse_dock_yaml(text + 'dock_pose_measured: false\n').measured is False
    assert core.parse_dock_yaml(text + 'dock_pose_measured: true\n').measured is True


def test_normalise_polygon_drops_geojson_closing_vertex():
    ring = [(0.0, 0.0), (2.0, 0.0), (2.0, 1.0), (0.0, 0.0)]
    assert core.normalise_polygon(ring) == ring[:-1]
    assert core.normalise_polygon(ring[:-1]) == ring[:-1]


# ---------------------------------------------------------------- path (channel) metadata

LINE = [(0.0, 5.0), (12.0, 5.0), (12.0, 9.5)]


def _with_path():
    s = _store()
    poly = core.buffer_polyline(LINE, 0.35)
    s.add_area('Path 1', poly, True)
    return s


def test_set_channel_on_navigation_area_and_roundtrip():
    s = _with_path()
    ok, msg = s.set_channel(1, LINE, 0.7)
    assert ok, msg
    text = core.format_areas_dat(s.areas)
    assert 'area_1_channel: 0,5;12,5;12,9.5\n' in text
    assert 'area_1_channel_width_m: 0.7\n' in text
    assert 'area_0_channel' not in text           # plain areas carry no keys
    areas, _ = core.parse_areas_dat(text)
    assert areas[1].channel == LINE and areas[1].channel_width_m == pytest.approx(0.7)
    assert areas[0].channel is None
    s2 = core.MapStore()
    s2.load(areas)                                 # load keeps the metadata
    assert s2.areas[1].channel == LINE


def test_set_channel_validation_and_clear():
    s = _with_path()
    assert not s.set_channel(0, LINE, 0.7)[0]      # mowing area
    assert not s.set_channel(5, LINE, 0.7)[0]      # bad index
    assert not s.set_channel(1, LINE[:1], 0.7)[0]  # one point
    assert not s.set_channel(1, LINE, 0.0)[0]      # width
    assert not s.set_channel(1, [(0, 0), (float('nan'), 1)], 0.7)[0]
    assert s.set_channel(1, LINE, 0.7)[0]
    assert s.set_channel(1, None)[0]
    assert s.areas[1].channel is None and s.areas[1].channel_width_m == 0.0


def test_old_reader_format_unchanged_without_channel():
    """A file without channel keys parses as before; unknown keys are ignored."""
    s = _with_path()
    text = core.format_areas_dat(s.areas)
    assert '_channel' not in text
    areas, _ = core.parse_areas_dat(text + 'area_1_channel: 1,1\n')  # 1 point -> ignored
    assert areas[1].channel is None


def test_channel_json_helpers():
    s = _with_path()
    assert core.channel_to_json(s.areas[1]) == '{}'
    s.set_channel(1, LINE, 0.7)
    obj = json.loads(core.channel_to_json(s.areas[1]))
    assert obj == {'points': [[0.0, 5.0], [12.0, 5.0], [12.0, 9.5]], 'width_m': 0.7}
    ok, _, pts, w = core.parse_channel_json(json.dumps(obj))
    assert ok and pts == LINE and w == 0.7
    assert core.parse_channel_json('{}')[2] is None
    assert core.parse_channel_json('')[0]
    assert not core.parse_channel_json('[1]')[0]
    assert not core.parse_channel_json('{"points": [[1]]}')[0]
    assert not core.parse_channel_json('nope')[0]


def test_path_band_is_free_in_nav_mask_but_not_mowed():
    """A path is a navigation area: the band is free in /nav_keepout_mask
    (the gap between the lawn and a far point becomes drivable) while the
    mowing side (area list the mission mows) never includes it."""
    s = _with_path()
    s.set_channel(1, LINE, 0.7)
    spec = core.grid_for_polygons([a.polygon for a in s.areas], 0.05, 1.0)
    nav = core.build_nav_mask(s.areas, spec)
    # (11, 5) lies outside the 10 m lawn but inside the band
    cx, cy = int((11.0 - spec.origin_x) / spec.resolution), int((5.0 - spec.origin_y) / spec.resolution)
    assert nav[cy, cx] == core.FREE
    # a point beside the band (outside both) stays lethal
    fx, fy = int((11.0 - spec.origin_x) / spec.resolution), int((8.0 - spec.origin_y) / spec.resolution)
    assert nav[fy, fx] != core.FREE
    assert [a.name for a in s.areas if not a.is_navigation] == ['lawn']



# ---------------------------------------------------------------- soft band / return corridor

def _nav_setup(robot=None, soft_band=1.5):
    s = core.MapStore()
    s.add_area('lawn', SQUARE, False, [(HOLE, 'tree', core.SOURCE_USER)])
    polys = [a.polygon for a in s.areas] + ([[robot]] if robot else [])
    spec = core.grid_for_polygons(polys, 0.1, 2.0)
    base = core.build_nav_mask(s.areas, spec, 0.8, 0.10, None, soft_band)
    return s, spec, base


def test_nav_mask_soft_band():
    s, spec, nav = _nav_setup()
    assert _cell(spec, nav, 5.0, 5.0) == core.LETHAL          # obstacle
    assert _cell(spec, nav, 2.0, 2.0) == core.FREE
    assert _cell(spec, nav, 10.7, 5.0) == core.FREE           # within nav_margin
    assert _cell(spec, nav, 11.5, 5.0) == core.SOFT_COST      # 0.7 m past the margin
    assert _cell(spec, nav, 11.95, 5.0) == core.SOFT_COST     # 1.15 m past the margin
    assert _cell(spec, nav, 11.85, 11.85) == core.LETHAL      # corner: 2.62 m from the area
    without = core.build_nav_mask(s.areas, spec, 0.8, 0.10)
    assert _cell(spec, without, 11.5, 5.0) == core.LETHAL     # band disabled by default
    assert core.SOFT_COST < core.LETHAL


def test_return_corridor_freed_from_robot_off_map():
    robot = (16.0, 5.0)
    s, spec, base = _nav_setup(robot)
    assert not core.is_free_at(base, spec, *robot)
    rc = core.return_corridor(robot[0], robot[1], base, spec, 0.8, 15.0)
    assert rc is not None and rc.connected
    assert rc.gap_m == pytest.approx(16.0 - 10.8, abs=0.1)
    nav = core.build_nav_mask(s.areas, spec, 0.8, 0.10, None, 1.5, rc)
    for x in np.arange(10.8, 16.0, 0.1):                     # whole line robot -> area free
        assert _cell(spec, nav, x, 5.0) == core.FREE
    assert _cell(spec, nav, 16.0, 5.7) == core.FREE           # width 2 * nav_margin
    assert _cell(spec, nav, 14.0, 7.0) != core.FREE           # outside the capsule
    assert len(rc.polygon()) > 4


def test_return_corridor_none_when_inside_or_in_margin():
    s, spec, base = _nav_setup()
    assert core.return_corridor(2.0, 2.0, base, spec, 0.8) is None
    assert core.return_corridor(10.5, 5.0, base, spec, 0.8) is None


def test_return_corridor_too_far_not_connected():
    robot = (30.0, 5.0)
    s, spec, base = _nav_setup(robot)
    rc = core.return_corridor(robot[0], robot[1], base, spec, 0.8, 15.0)
    assert rc is not None and not rc.connected and rc.gap_m > 15.0


def test_return_corridor_obstacles_override():
    s = core.MapStore()
    blocker = [(12.0, 4.0), (13.0, 4.0), (13.0, 6.0), (12.0, 6.0)]
    s.add_area('lawn', SQUARE, False, [(blocker, 'rock', core.SOURCE_USER)])
    robot = (16.0, 5.0)
    spec = core.grid_for_polygons([SQUARE, [robot]], 0.1, 2.0)
    base = core.build_nav_mask(s.areas, spec, 0.8, 0.10, None, 1.5)
    rc = core.return_corridor(robot[0], robot[1], base, spec, 0.8, 15.0)
    nav = core.build_nav_mask(s.areas, spec, 0.8, 0.10, None, 1.5, rc)
    assert _cell(spec, nav, 12.5, 5.0) == core.LETHAL
    assert _cell(spec, nav, 15.0, 5.0) == core.FREE


def _path_case():
    """Lawn x 2.5..8.5 (dock (0,0) yaw 0 -> approach (0.8,0) -> gap to x=2.5);
    a drawn path from the approach curving up via y=2 into the lawn."""
    s, dock = _far_dock_case(2.5)
    line = [(0.8, 0.0), (0.8, 2.0), (3.0, 2.0)]
    s.add_area('Dock path', core.buffer_polyline(line, 0.35), is_navigation=True)
    ok, _ = s.set_channel(1, line, 0.7)
    assert ok
    return s, dock


def test_nav_mask_path_margin_only_on_navigation_areas():
    s, dock = _path_case()
    spec = core.grid_for_polygons([a.polygon for a in s.areas], 0.1, 3.0)
    nav = core.build_nav_mask(s.areas, spec, 0.8, 0.10, None, 0.0, None, 0.15)
    assert _cell(spec, nav, 1.8, 1.0) == core.FREE        # lawn grown by 0.8
    assert _cell(spec, nav, 1.6, 1.0) == core.LETHAL      # beyond 0.8 of the lawn
    assert _cell(spec, nav, 0.8, 1.0) == core.FREE        # on the path
    assert _cell(spec, nav, 0.8 + 0.45, 1.0) == core.FREE  # half width 0.35 + 0.15
    assert _cell(spec, nav, 0.8 + 0.65, 1.0) == core.LETHAL
    # default path_margin = nav_margin (old behaviour)
    old = core.build_nav_mask(s.areas, spec, 0.8, 0.10)
    assert _cell(spec, old, 0.8 + 0.95, 1.0) == core.FREE


def test_dock_corridor_soft_when_user_path_exists():
    s, dock = _path_case()
    assert core.has_user_path(s.areas)
    corridor = core.dock_corridor(dock, s.areas, 0.8, 0.8, 5.0)
    # approach (0.8, 0) lies inside the path polygon -> 2-point corridor; build a
    # 3-point one by hand to test the soft leg
    corridor = core.DockCorridor([(0.0, 0.0), (0.8, 0.0), (2.5, 0.0)], 0.35, True, 1.7)
    spec = core.grid_for_polygons([a.polygon for a in s.areas] + [corridor.polygon()], 0.1, 3.0)
    nav = core.build_nav_mask(s.areas, spec, 0.8, 0.10, corridor, 1.5, None, 0.15)
    assert _cell(spec, nav, 0.0, 0.0) == core.FREE        # dock -> approach capsule free
    assert _cell(spec, nav, 0.8, 0.0) == core.FREE
    assert _cell(spec, nav, 1.15, 0.0) == core.FREE       # within 0.35 beyond approach
    assert _cell(spec, nav, 1.5, -0.1) == core.SOFT_COST  # automatic leg is soft now
    hard = core.build_nav_mask(s.areas, spec, 0.8, 0.10, corridor, 1.5, None, 0.15, False)
    assert _cell(spec, hard, 1.5, -0.1) == core.FREE
    # without a user path the corridor stays free
    plain = core.MapStore()
    plain.load([s.areas[0]])
    assert not core.has_user_path(plain.areas)
    nav2 = core.build_nav_mask(plain.areas, spec, 0.8, 0.10, corridor, 1.5, None, 0.15)
    assert _cell(spec, nav2, 1.5, -0.1) == core.FREE


def test_soft_leg_without_soft_band_and_mowing_mask_unchanged():
    s, dock = _path_case()
    corridor = core.DockCorridor([(0.0, 0.0), (0.8, 0.0), (2.5, 0.0)], 0.35, True, 1.7)
    spec = core.grid_for_polygons([a.polygon for a in s.areas] + [corridor.polygon()], 0.1, 3.0)
    m1 = core.build_keepout_mask(s.areas, spec, None, 0.0, True)
    nav = core.build_nav_mask(s.areas, spec, 0.8, 0.10, corridor, 0.0, None, 0.15)
    assert _cell(spec, nav, 1.5, -0.1) == core.SOFT_COST
    assert np.array_equal(m1, core.build_keepout_mask(s.areas, spec, None, 0.0, True))
    assert _cell(spec, m1, 4.0, 0.0) == core.FREE         # lawn polygon unchanged


def test_nav_mask_prefer_paths_in_areas():
    s, dock = _path_case()
    corridor = core.DockCorridor([(0.0, 0.0), (0.8, 0.0), (2.5, 0.0)], 0.35, True, 1.7)
    spec = core.grid_for_polygons([a.polygon for a in s.areas] + [corridor.polygon()], 0.1, 3.0)
    nav = core.build_nav_mask(s.areas, spec, 0.8, 0.10, corridor, 1.5, None, 0.15,
                              True, True, 40)
    assert _cell(spec, nav, 5.0, 0.0) == 40               # lawn interior: transit cost
    assert _cell(spec, nav, 1.8, 1.0) == 40               # lawn margin too
    assert _cell(spec, nav, 2.9, 2.0) == core.FREE        # path band inside the lawn
    assert _cell(spec, nav, 0.8, 1.0) == core.FREE        # path band outside the lawn
    assert _cell(spec, nav, 0.0, 0.0) == core.FREE        # dock -> approach capsule
    assert _cell(spec, nav, 0.4, 0.0) == core.FREE
    assert _cell(spec, nav, 1.6, 1.0) == core.SOFT_COST   # soft band unchanged
    # disabled: lawn is free again
    off = core.build_nav_mask(s.areas, spec, 0.8, 0.10, corridor, 1.5, None, 0.15, True, False)
    assert _cell(spec, off, 5.0, 0.0) == core.FREE
    # without a user path the lawn stays free even when enabled
    plain = core.MapStore()
    plain.add_area('Lawn', s.areas[0].polygon)
    nopath = core.build_nav_mask(plain.areas, spec, 0.8, 0.10, None, 0.0, None, 0.15, True, True)
    assert _cell(spec, nopath, 5.0, 0.0) == core.FREE


def test_nav_mask_path_centre_low_profile():
    s, dock = _path_case()
    spec = core.grid_for_polygons([a.polygon for a in s.areas], 0.1, 3.0)
    nav = core.build_nav_mask(s.areas, spec, 0.8, 0.10, None, 1.5, None, 0.15,
                              True, True, 60, 30)
    # vertical leg x=0.8 (y 0..2), outside the lawn: 0 on the centreline,
    # rising toward the band edge (half width 0.35 + margin 0.15 = 0.5 m)
    centre = _cell(spec, nav, 0.85, 1.0)
    mid = _cell(spec, nav, 1.05, 1.0)
    edge = _cell(spec, nav, 1.25, 1.0)
    assert centre <= 5
    assert centre < mid < edge <= 30
    # symmetric on the other side
    assert abs(_cell(spec, nav, 0.55, 1.0) - mid) <= 3
    # lawn interior costs more than any part of the band; soft band untouched
    assert _cell(spec, nav, 5.0, 0.0) == 60
    assert _cell(spec, nav, 2.9, 2.0) < 60                # band inside the lawn
    assert _cell(spec, nav, 1.6, 1.0) == core.SOFT_COST
    # every band cell stays on the map (return corridor / nearest free point)
    assert core.is_free_at(nav, spec, 1.25, 1.0)
    # path_edge_cost 0 keeps the old flat band
    flat = core.build_nav_mask(s.areas, spec, 0.8, 0.10, None, 1.5, None, 0.15,
                               True, True, 60, 0)
    assert _cell(spec, flat, 1.25, 1.0) == core.FREE


def test_nav_mask_path_profile_overlap_takes_minimum():
    s, dock = _path_case()
    line = [(0.8, 2.0), (0.8, 4.0)]
    s.add_area('Branch', core.buffer_polyline(line, 0.35), is_navigation=True)
    ok, _ = s.set_channel(2, line, 0.7)
    assert ok
    spec = core.grid_for_polygons([a.polygon for a in s.areas], 0.1, 3.0)
    nav = core.build_nav_mask(s.areas, spec, 0.8, 0.10, None, 0.0, None, 0.15,
                              True, True, 60, 30)
    # (0.85, 2.05) is on both centrelines: stays ~0 whatever the paint order
    assert _cell(spec, nav, 0.85, 2.05) <= 5


def test_return_corridor_treats_transit_cost_as_on_map():
    s, dock = _path_case()
    spec = core.grid_for_polygons([a.polygon for a in s.areas], 0.1, 3.0)
    nav = core.build_nav_mask(s.areas, spec, 0.8, 0.10, None, 1.5, None, 0.15, True, True, 40)
    assert core.is_free_at(nav, spec, 5.0, 0.0)
    assert core.return_corridor(5.0, 0.0, nav, spec, 0.35) is None
    assert not core.is_free_at(nav, spec, 1.6, 1.0)        # soft band still off-map


# --- drawn polygons keep every far-apart corner (square -> triangle bug) ---

def test_normalise_square_keeps_four_corners_ccw_and_cw():
    sq = [(0, 0), (3, 0), (3, 3), (0, 3), (0, 0)]
    assert len(core.normalise_polygon(sq)) == 4
    assert len(core.normalise_polygon(list(reversed(sq)))) == 4


def test_normalise_square_last_click_near_first_point_kept():
    # 4th corner 20 cm from the first: a real corner, not a closing repeat
    poly = core.normalise_polygon([(0, 0), (3, 0), (3, 3), (0.2, 0.0), (0, 0)])
    assert len(poly) == 4


def test_normalise_drops_only_vertices_within_5cm():
    poly = core.normalise_polygon([(0, 0), (3, 0), (3.03, 0.0), (3, 3), (0, 3), (0.02, 0.0)])
    assert poly == [(0.0, 0.0), (3.0, 0.0), (3.0, 3.0), (0.0, 3.0)]


def test_normalise_keeps_collinear_points():
    assert len(core.normalise_polygon([(0, 0), (1.5, 0), (3, 0), (3, 3), (0, 3)])) == 5
