# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x05mower\x1a\x19google/protobuf/any.proto\"7\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\x0b\n\x03lat\x18\x03 \x01(\x01\x12\x0b\n\x03lon\x18\x04 \x01(\x01\"r\n\x04Pose\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\x12\x0b\n\x03yaw\x18\x03 \x01(\x01\x12\t\n\x01x\x18\x04 \x01(\x01\x12\t\n\x01y\x18\x05 \x01(\x01\x12\x0c\n\x04roll\x18\x06 \x01(\x01\x12\r\n\x05pitch\x18\x07 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x08 \x01(\x01\")\n\x07Polygon\x12\x1e\n\x08\x62oundary\x18\x01 \x03(\x0b\x32\x0c.mower.Point\"\xd0\x01\n\nTrackPoint\x12\x1b\n\x05point\x18\x01 \x01(\x0b\x32\x0c.mower.Point\x12\r\n\x05theta\x18\x02 \x01(\x02\x12$\n\x04type\x18\x03 \x01(\x0e\x32\x16.mower.TrackPoint.Type\x12\x12\n\ntime_stamp\x18\x04 \x01(\x05\x12\x0c\n\x04roll\x18\x05 \x01(\x02\x12\r\n\x05pitch\x18\x06 \x01(\x02\x12\x0f\n\x07quality\x18\x07 \x01(\x05\".\n\x04Type\x12\n\n\x06NORMAL\x10\x00\x12\r\n\tSMALL_CUT\x10\x01\x12\x0b\n\x07\x42IG_CUT\x10\x02\"(\n\x05Twist\x12\x0e\n\x06linear\x18\x01 \x01(\x02\x12\x0f\n\x07\x61ngular\x18\x02 \x01(\x02\"%\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\tB\x06Z\x04.;pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004.;pb'
  _POINT._serialized_start=50
  _POINT._serialized_end=105
  _POSE._serialized_start=107
  _POSE._serialized_end=221
  _POLYGON._serialized_start=223
  _POLYGON._serialized_end=264
  _TRACKPOINT._serialized_start=267
  _TRACKPOINT._serialized_end=475
  _TRACKPOINT_TYPE._serialized_start=429
  _TRACKPOINT_TYPE._serialized_end=475
  _TWIST._serialized_start=477
  _TWIST._serialized_end=517
  _RESPONSE._serialized_start=519
  _RESPONSE._serialized_end=556
# @@protoc_insertion_point(module_scope)
