# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63onfig.proto\x12\x0cmower.config\x1a\x0c\x63ommon.proto\"u\n\x0cSetConfigReq\x12\x36\n\x06\x63onfig\x18\x01 \x03(\x0b\x32&.mower.config.SetConfigReq.ConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x87\x01\n\x0cSetConfigRsp\x12\x38\n\nerror_code\x18\x01 \x01(\x0e\x32$.mower.config.SetConfigRsp.ErrorCode\x12\x0b\n\x03msg\x18\x02 \x01(\t\"0\n\tErrorCode\x12\x11\n\rError_Success\x10\x00\x12\x10\n\x0c\x45rror_Failed\x10\x01\"8\n\x0cGetConfigReq\x12(\n\x04keys\x18\x01 \x03(\x0e\x32\x1a.mower.config.ParameterKey\"\xee\x01\n\x0cGetConfigRsp\x12\x38\n\nerror_code\x18\x01 \x01(\x0e\x32$.mower.config.GetConfigRsp.ErrorCode\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x36\n\x06\x63onfig\x18\x03 \x03(\x0b\x32&.mower.config.GetConfigRsp.ConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"0\n\tErrorCode\x12\x11\n\rError_Success\x10\x00\x12\x10\n\x0c\x45rror_Failed\x10\x01\"\x11\n\x0f\x46\x61\x63toryResetReq\"\x11\n\x0f\x46\x61\x63toryResetRsp\"\x0e\n\x0cRebootRTKReq\"\x0e\n\x0cRebootRTKRsp\"9\n\x13\x46illLightControlReq\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08\x12\x12\n\nbrightness\x18\x02 \x01(\x05\"\x95\x01\n\x13\x46illLightControlRsp\x12?\n\nerror_code\x18\x01 \x01(\x0e\x32+.mower.config.FillLightControlRsp.ErrorCode\x12\x0b\n\x03msg\x18\x02 \x01(\t\"0\n\tErrorCode\x12\x11\n\rError_Success\x10\x00\x12\x10\n\x0c\x45rror_Failed\x10\x01*\xd8\x01\n\x0cParameterKey\x12\x07\n\x03\x41LL\x10\x00\x12\x0e\n\nDeviceLock\x10\x01\x12\x1b\n\x17Net4GAllowUploadPicture\x10\x02\x12\r\n\tSetVolume\x10\x03\x12\x16\n\x12SetLightBrightness\x10\x04\x12\x0f\n\x0bSetDarkMode\x10\x05\x12\x15\n\x11\x45nableAutoUpgrade\x10\x06\x12\x0e\n\nEnableNRTK\x10\x07\x12\x0f\n\x0bNRTKNetMode\x10\x08\x12\x0f\n\x0b\x44\x61rkModeDND\x10\t\x12\x11\n\rFillLightAuto\x10\nB\x06Z\x04.;pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004.;pb'
  _SETCONFIGREQ_CONFIGENTRY._options = None
  _SETCONFIGREQ_CONFIGENTRY._serialized_options = b'8\001'
  _GETCONFIGRSP_CONFIGENTRY._options = None
  _GETCONFIGRSP_CONFIGENTRY._serialized_options = b'8\001'
  _PARAMETERKEY._serialized_start=882
  _PARAMETERKEY._serialized_end=1098
  _SETCONFIGREQ._serialized_start=44
  _SETCONFIGREQ._serialized_end=161
  _SETCONFIGREQ_CONFIGENTRY._serialized_start=116
  _SETCONFIGREQ_CONFIGENTRY._serialized_end=161
  _SETCONFIGRSP._serialized_start=164
  _SETCONFIGRSP._serialized_end=299
  _SETCONFIGRSP_ERRORCODE._serialized_start=251
  _SETCONFIGRSP_ERRORCODE._serialized_end=299
  _GETCONFIGREQ._serialized_start=301
  _GETCONFIGREQ._serialized_end=357
  _GETCONFIGRSP._serialized_start=360
  _GETCONFIGRSP._serialized_end=598
  _GETCONFIGRSP_CONFIGENTRY._serialized_start=116
  _GETCONFIGRSP_CONFIGENTRY._serialized_end=161
  _GETCONFIGRSP_ERRORCODE._serialized_start=251
  _GETCONFIGRSP_ERRORCODE._serialized_end=299
  _FACTORYRESETREQ._serialized_start=600
  _FACTORYRESETREQ._serialized_end=617
  _FACTORYRESETRSP._serialized_start=619
  _FACTORYRESETRSP._serialized_end=636
  _REBOOTRTKREQ._serialized_start=638
  _REBOOTRTKREQ._serialized_end=652
  _REBOOTRTKRSP._serialized_start=654
  _REBOOTRTKRSP._serialized_end=668
  _FILLLIGHTCONTROLREQ._serialized_start=670
  _FILLLIGHTCONTROLREQ._serialized_end=727
  _FILLLIGHTCONTROLRSP._serialized_start=730
  _FILLLIGHTCONTROLRSP._serialized_end=879
  _FILLLIGHTCONTROLRSP_ERRORCODE._serialized_start=251
  _FILLLIGHTCONTROLRSP_ERRORCODE._serialized_end=299
# @@protoc_insertion_point(module_scope)
