# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='config.proto',
  package='mower.config',
  syntax='proto3',
  serialized_options=b'Z\004.;pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63onfig.proto\x12\x0cmower.config\x1a\x0c\x63ommon.proto\"u\n\x0cSetConfigReq\x12\x36\n\x06\x63onfig\x18\x01 \x03(\x0b\x32&.mower.config.SetConfigReq.ConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x87\x01\n\x0cSetConfigRsp\x12\x38\n\nerror_code\x18\x01 \x01(\x0e\x32$.mower.config.SetConfigRsp.ErrorCode\x12\x0b\n\x03msg\x18\x02 \x01(\t\"0\n\tErrorCode\x12\x11\n\rError_Success\x10\x00\x12\x10\n\x0c\x45rror_Failed\x10\x01\"8\n\x0cGetConfigReq\x12(\n\x04keys\x18\x01 \x03(\x0e\x32\x1a.mower.config.ParameterKey\"\xee\x01\n\x0cGetConfigRsp\x12\x38\n\nerror_code\x18\x01 \x01(\x0e\x32$.mower.config.GetConfigRsp.ErrorCode\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x36\n\x06\x63onfig\x18\x03 \x03(\x0b\x32&.mower.config.GetConfigRsp.ConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"0\n\tErrorCode\x12\x11\n\rError_Success\x10\x00\x12\x10\n\x0c\x45rror_Failed\x10\x01\"\x11\n\x0f\x46\x61\x63toryResetReq\"\x11\n\x0f\x46\x61\x63toryResetRsp\"\x0e\n\x0cRebootRTKReq\"\x0e\n\x0cRebootRTKRsp\"9\n\x13\x46illLightControlReq\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08\x12\x12\n\nbrightness\x18\x02 \x01(\x05\"\x95\x01\n\x13\x46illLightControlRsp\x12?\n\nerror_code\x18\x01 \x01(\x0e\x32+.mower.config.FillLightControlRsp.ErrorCode\x12\x0b\n\x03msg\x18\x02 \x01(\t\"0\n\tErrorCode\x12\x11\n\rError_Success\x10\x00\x12\x10\n\x0c\x45rror_Failed\x10\x01*\xd8\x01\n\x0cParameterKey\x12\x07\n\x03\x41LL\x10\x00\x12\x0e\n\nDeviceLock\x10\x01\x12\x1b\n\x17Net4GAllowUploadPicture\x10\x02\x12\r\n\tSetVolume\x10\x03\x12\x16\n\x12SetLightBrightness\x10\x04\x12\x0f\n\x0bSetDarkMode\x10\x05\x12\x15\n\x11\x45nableAutoUpgrade\x10\x06\x12\x0e\n\nEnableNRTK\x10\x07\x12\x0f\n\x0bNRTKNetMode\x10\x08\x12\x0f\n\x0b\x44\x61rkModeDND\x10\t\x12\x11\n\rFillLightAuto\x10\nB\x06Z\x04.;pbb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])

_PARAMETERKEY = _descriptor.EnumDescriptor(
  name='ParameterKey',
  full_name='mower.config.ParameterKey',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DeviceLock', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Net4GAllowUploadPicture', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SetVolume', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SetLightBrightness', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SetDarkMode', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EnableAutoUpgrade', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EnableNRTK', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NRTKNetMode', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DarkModeDND', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FillLightAuto', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=882,
  serialized_end=1098,
)
_sym_db.RegisterEnumDescriptor(_PARAMETERKEY)

ParameterKey = enum_type_wrapper.EnumTypeWrapper(_PARAMETERKEY)
ALL = 0
DeviceLock = 1
Net4GAllowUploadPicture = 2
SetVolume = 3
SetLightBrightness = 4
SetDarkMode = 5
EnableAutoUpgrade = 6
EnableNRTK = 7
NRTKNetMode = 8
DarkModeDND = 9
FillLightAuto = 10


_SETCONFIGRSP_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='mower.config.SetConfigRsp.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Error_Success', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Error_Failed', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=251,
  serialized_end=299,
)
_sym_db.RegisterEnumDescriptor(_SETCONFIGRSP_ERRORCODE)

_GETCONFIGRSP_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='mower.config.GetConfigRsp.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Error_Success', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Error_Failed', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=251,
  serialized_end=299,
)
_sym_db.RegisterEnumDescriptor(_GETCONFIGRSP_ERRORCODE)

_FILLLIGHTCONTROLRSP_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='mower.config.FillLightControlRsp.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Error_Success', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Error_Failed', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=251,
  serialized_end=299,
)
_sym_db.RegisterEnumDescriptor(_FILLLIGHTCONTROLRSP_ERRORCODE)


_SETCONFIGREQ_CONFIGENTRY = _descriptor.Descriptor(
  name='ConfigEntry',
  full_name='mower.config.SetConfigReq.ConfigEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mower.config.SetConfigReq.ConfigEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='mower.config.SetConfigReq.ConfigEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=161,
)

_SETCONFIGREQ = _descriptor.Descriptor(
  name='SetConfigReq',
  full_name='mower.config.SetConfigReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='mower.config.SetConfigReq.config', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SETCONFIGREQ_CONFIGENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=161,
)


_SETCONFIGRSP = _descriptor.Descriptor(
  name='SetConfigRsp',
  full_name='mower.config.SetConfigRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='mower.config.SetConfigRsp.error_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='mower.config.SetConfigRsp.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SETCONFIGRSP_ERRORCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=299,
)


_GETCONFIGREQ = _descriptor.Descriptor(
  name='GetConfigReq',
  full_name='mower.config.GetConfigReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keys', full_name='mower.config.GetConfigReq.keys', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=357,
)


_GETCONFIGRSP_CONFIGENTRY = _descriptor.Descriptor(
  name='ConfigEntry',
  full_name='mower.config.GetConfigRsp.ConfigEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mower.config.GetConfigRsp.ConfigEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='mower.config.GetConfigRsp.ConfigEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=161,
)

_GETCONFIGRSP = _descriptor.Descriptor(
  name='GetConfigRsp',
  full_name='mower.config.GetConfigRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='mower.config.GetConfigRsp.error_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='mower.config.GetConfigRsp.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config', full_name='mower.config.GetConfigRsp.config', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GETCONFIGRSP_CONFIGENTRY, ],
  enum_types=[
    _GETCONFIGRSP_ERRORCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=598,
)


_FACTORYRESETREQ = _descriptor.Descriptor(
  name='FactoryResetReq',
  full_name='mower.config.FactoryResetReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=600,
  serialized_end=617,
)


_FACTORYRESETRSP = _descriptor.Descriptor(
  name='FactoryResetRsp',
  full_name='mower.config.FactoryResetRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=619,
  serialized_end=636,
)


_REBOOTRTKREQ = _descriptor.Descriptor(
  name='RebootRTKReq',
  full_name='mower.config.RebootRTKReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=638,
  serialized_end=652,
)


_REBOOTRTKRSP = _descriptor.Descriptor(
  name='RebootRTKRsp',
  full_name='mower.config.RebootRTKRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=654,
  serialized_end=668,
)


_FILLLIGHTCONTROLREQ = _descriptor.Descriptor(
  name='FillLightControlReq',
  full_name='mower.config.FillLightControlReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='enable', full_name='mower.config.FillLightControlReq.enable', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='brightness', full_name='mower.config.FillLightControlReq.brightness', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=670,
  serialized_end=727,
)


_FILLLIGHTCONTROLRSP = _descriptor.Descriptor(
  name='FillLightControlRsp',
  full_name='mower.config.FillLightControlRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='mower.config.FillLightControlRsp.error_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='mower.config.FillLightControlRsp.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FILLLIGHTCONTROLRSP_ERRORCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=730,
  serialized_end=879,
)

_SETCONFIGREQ_CONFIGENTRY.containing_type = _SETCONFIGREQ
_SETCONFIGREQ.fields_by_name['config'].message_type = _SETCONFIGREQ_CONFIGENTRY
_SETCONFIGRSP.fields_by_name['error_code'].enum_type = _SETCONFIGRSP_ERRORCODE
_SETCONFIGRSP_ERRORCODE.containing_type = _SETCONFIGRSP
_GETCONFIGREQ.fields_by_name['keys'].enum_type = _PARAMETERKEY
_GETCONFIGRSP_CONFIGENTRY.containing_type = _GETCONFIGRSP
_GETCONFIGRSP.fields_by_name['error_code'].enum_type = _GETCONFIGRSP_ERRORCODE
_GETCONFIGRSP.fields_by_name['config'].message_type = _GETCONFIGRSP_CONFIGENTRY
_GETCONFIGRSP_ERRORCODE.containing_type = _GETCONFIGRSP
_FILLLIGHTCONTROLRSP.fields_by_name['error_code'].enum_type = _FILLLIGHTCONTROLRSP_ERRORCODE
_FILLLIGHTCONTROLRSP_ERRORCODE.containing_type = _FILLLIGHTCONTROLRSP
DESCRIPTOR.message_types_by_name['SetConfigReq'] = _SETCONFIGREQ
DESCRIPTOR.message_types_by_name['SetConfigRsp'] = _SETCONFIGRSP
DESCRIPTOR.message_types_by_name['GetConfigReq'] = _GETCONFIGREQ
DESCRIPTOR.message_types_by_name['GetConfigRsp'] = _GETCONFIGRSP
DESCRIPTOR.message_types_by_name['FactoryResetReq'] = _FACTORYRESETREQ
DESCRIPTOR.message_types_by_name['FactoryResetRsp'] = _FACTORYRESETRSP
DESCRIPTOR.message_types_by_name['RebootRTKReq'] = _REBOOTRTKREQ
DESCRIPTOR.message_types_by_name['RebootRTKRsp'] = _REBOOTRTKRSP
DESCRIPTOR.message_types_by_name['FillLightControlReq'] = _FILLLIGHTCONTROLREQ
DESCRIPTOR.message_types_by_name['FillLightControlRsp'] = _FILLLIGHTCONTROLRSP
DESCRIPTOR.enum_types_by_name['ParameterKey'] = _PARAMETERKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetConfigReq = _reflection.GeneratedProtocolMessageType('SetConfigReq', (_message.Message,), {

  'ConfigEntry' : _reflection.GeneratedProtocolMessageType('ConfigEntry', (_message.Message,), {
    'DESCRIPTOR' : _SETCONFIGREQ_CONFIGENTRY,
    '__module__' : 'config_pb2'
    # @@protoc_insertion_point(class_scope:mower.config.SetConfigReq.ConfigEntry)
    })
  ,
  'DESCRIPTOR' : _SETCONFIGREQ,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:mower.config.SetConfigReq)
  })
_sym_db.RegisterMessage(SetConfigReq)
_sym_db.RegisterMessage(SetConfigReq.ConfigEntry)

SetConfigRsp = _reflection.GeneratedProtocolMessageType('SetConfigRsp', (_message.Message,), {
  'DESCRIPTOR' : _SETCONFIGRSP,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:mower.config.SetConfigRsp)
  })
_sym_db.RegisterMessage(SetConfigRsp)

GetConfigReq = _reflection.GeneratedProtocolMessageType('GetConfigReq', (_message.Message,), {
  'DESCRIPTOR' : _GETCONFIGREQ,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:mower.config.GetConfigReq)
  })
_sym_db.RegisterMessage(GetConfigReq)

GetConfigRsp = _reflection.GeneratedProtocolMessageType('GetConfigRsp', (_message.Message,), {

  'ConfigEntry' : _reflection.GeneratedProtocolMessageType('ConfigEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETCONFIGRSP_CONFIGENTRY,
    '__module__' : 'config_pb2'
    # @@protoc_insertion_point(class_scope:mower.config.GetConfigRsp.ConfigEntry)
    })
  ,
  'DESCRIPTOR' : _GETCONFIGRSP,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:mower.config.GetConfigRsp)
  })
_sym_db.RegisterMessage(GetConfigRsp)
_sym_db.RegisterMessage(GetConfigRsp.ConfigEntry)

FactoryResetReq = _reflection.GeneratedProtocolMessageType('FactoryResetReq', (_message.Message,), {
  'DESCRIPTOR' : _FACTORYRESETREQ,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:mower.config.FactoryResetReq)
  })
_sym_db.RegisterMessage(FactoryResetReq)

FactoryResetRsp = _reflection.GeneratedProtocolMessageType('FactoryResetRsp', (_message.Message,), {
  'DESCRIPTOR' : _FACTORYRESETRSP,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:mower.config.FactoryResetRsp)
  })
_sym_db.RegisterMessage(FactoryResetRsp)

RebootRTKReq = _reflection.GeneratedProtocolMessageType('RebootRTKReq', (_message.Message,), {
  'DESCRIPTOR' : _REBOOTRTKREQ,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:mower.config.RebootRTKReq)
  })
_sym_db.RegisterMessage(RebootRTKReq)

RebootRTKRsp = _reflection.GeneratedProtocolMessageType('RebootRTKRsp', (_message.Message,), {
  'DESCRIPTOR' : _REBOOTRTKRSP,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:mower.config.RebootRTKRsp)
  })
_sym_db.RegisterMessage(RebootRTKRsp)

FillLightControlReq = _reflection.GeneratedProtocolMessageType('FillLightControlReq', (_message.Message,), {
  'DESCRIPTOR' : _FILLLIGHTCONTROLREQ,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:mower.config.FillLightControlReq)
  })
_sym_db.RegisterMessage(FillLightControlReq)

FillLightControlRsp = _reflection.GeneratedProtocolMessageType('FillLightControlRsp', (_message.Message,), {
  'DESCRIPTOR' : _FILLLIGHTCONTROLRSP,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:mower.config.FillLightControlRsp)
  })
_sym_db.RegisterMessage(FillLightControlRsp)


DESCRIPTOR._options = None
_SETCONFIGREQ_CONFIGENTRY._options = None
_GETCONFIGRSP_CONFIGENTRY._options = None
# @@protoc_insertion_point(module_scope)
