# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: init.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='init.proto',
  package='mower.init',
  syntax='proto3',
  serialized_options=b'Z\004.;pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ninit.proto\x12\nmower.init\x1a\x0c\x63ommon.proto\"\xad\x01\n\x06\x43onfig\x12+\n\x07request\x18\x01 \x01(\x0b\x32\x1a.mower.init.Config.Request\x12!\n\x08response\x18\x02 \x01(\x0b\x32\x0f.mower.Response\x1a\x19\n\x07Request\x12\x0e\n\x06region\x18\x01 \x01(\t\"8\n\x0cResponseCode\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x42\x06Z\x04.;pbb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])



_CONFIG_RESPONSECODE = _descriptor.EnumDescriptor(
  name='ResponseCode',
  full_name='mower.init.Config.ResponseCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=158,
  serialized_end=214,
)
_sym_db.RegisterEnumDescriptor(_CONFIG_RESPONSECODE)


_CONFIG_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='mower.init.Config.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='region', full_name='mower.init.Config.Request.region', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=156,
)

_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='mower.init.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='mower.init.Config.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response', full_name='mower.init.Config.response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CONFIG_REQUEST, ],
  enum_types=[
    _CONFIG_RESPONSECODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=214,
)

_CONFIG_REQUEST.containing_type = _CONFIG
_CONFIG.fields_by_name['request'].message_type = _CONFIG_REQUEST
_CONFIG.fields_by_name['response'].message_type = common__pb2._RESPONSE
_CONFIG_RESPONSECODE.containing_type = _CONFIG
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {

  'Request' : _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
    'DESCRIPTOR' : _CONFIG_REQUEST,
    '__module__' : 'init_pb2'
    # @@protoc_insertion_point(class_scope:mower.init.Config.Request)
    })
  ,
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'init_pb2'
  # @@protoc_insertion_point(class_scope:mower.init.Config)
  })
_sym_db.RegisterMessage(Config)
_sym_db.RegisterMessage(Config.Request)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
