# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: init.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ninit.proto\x12\nmower.init\x1a\x0c\x63ommon.proto\"\xad\x01\n\x06\x43onfig\x12+\n\x07request\x18\x01 \x01(\x0b\x32\x1a.mower.init.Config.Request\x12!\n\x08response\x18\x02 \x01(\x0b\x32\x0f.mower.Response\x1a\x19\n\x07Request\x12\x0e\n\x06region\x18\x01 \x01(\t\"8\n\x0cResponseCode\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x42\x06Z\x04.;pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'init_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004.;pb'
  _CONFIG._serialized_start=41
  _CONFIG._serialized_end=214
  _CONFIG_REQUEST._serialized_start=131
  _CONFIG_REQUEST._serialized_end=156
  _CONFIG_RESPONSECODE._serialized_start=158
  _CONFIG_RESPONSECODE._serialized_end=214
# @@protoc_insertion_point(module_scope)
