# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: live.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlive.proto\x12\x05mower\"?\n\rPushStreamReq\x12\x0b\n\x03url\x18\x01 \x01(\t\x12!\n\x06\x63\x61mera\x18\x02 \x01(\x0e\x32\x11.mower.CameraType\"*\n\rPushStreamRsp\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"4\n\x0fStreamHeartbeat\x12!\n\x06\x63\x61mera\x18\x01 \x01(\x0e\x32\x11.mower.CameraType\"H\n\x0eMoveControlReq\x12\x10\n\x08linear_x\x18\x01 \x01(\x02\x12\x11\n\tangular_z\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\x03*C\n\nCameraType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05\x46RONT\x10\x01\x12\x08\n\x04LEFT\x10\x02\x12\t\n\x05RIGHT\x10\x03\x12\x08\n\x04\x42\x41\x43K\x10\x04\x42\x06Z\x04.;pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'live_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004.;pb'
  _CAMERATYPE._serialized_start=258
  _CAMERATYPE._serialized_end=325
  _PUSHSTREAMREQ._serialized_start=21
  _PUSHSTREAMREQ._serialized_end=84
  _PUSHSTREAMRSP._serialized_start=86
  _PUSHSTREAMRSP._serialized_end=128
  _STREAMHEARTBEAT._serialized_start=130
  _STREAMHEARTBEAT._serialized_end=182
  _MOVECONTROLREQ._serialized_start=184
  _MOVECONTROLREQ._serialized_end=256
# @@protoc_insertion_point(module_scope)
