# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: live.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='live.proto',
  package='mower',
  syntax='proto3',
  serialized_options=b'Z\004.;pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nlive.proto\x12\x05mower\"?\n\rPushStreamReq\x12\x0b\n\x03url\x18\x01 \x01(\t\x12!\n\x06\x63\x61mera\x18\x02 \x01(\x0e\x32\x11.mower.CameraType\"*\n\rPushStreamRsp\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"4\n\x0fStreamHeartbeat\x12!\n\x06\x63\x61mera\x18\x01 \x01(\x0e\x32\x11.mower.CameraType\"H\n\x0eMoveControlReq\x12\x10\n\x08linear_x\x18\x01 \x01(\x02\x12\x11\n\tangular_z\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\x03*C\n\nCameraType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05\x46RONT\x10\x01\x12\x08\n\x04LEFT\x10\x02\x12\t\n\x05RIGHT\x10\x03\x12\x08\n\x04\x42\x41\x43K\x10\x04\x42\x06Z\x04.;pbb\x06proto3'
)

_CAMERATYPE = _descriptor.EnumDescriptor(
  name='CameraType',
  full_name='mower.CameraType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FRONT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BACK', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=258,
  serialized_end=325,
)
_sym_db.RegisterEnumDescriptor(_CAMERATYPE)

CameraType = enum_type_wrapper.EnumTypeWrapper(_CAMERATYPE)
UNKNOWN = 0
FRONT = 1
LEFT = 2
RIGHT = 3
BACK = 4



_PUSHSTREAMREQ = _descriptor.Descriptor(
  name='PushStreamReq',
  full_name='mower.PushStreamReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='mower.PushStreamReq.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='camera', full_name='mower.PushStreamReq.camera', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=84,
)


_PUSHSTREAMRSP = _descriptor.Descriptor(
  name='PushStreamRsp',
  full_name='mower.PushStreamRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='mower.PushStreamRsp.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='mower.PushStreamRsp.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=128,
)


_STREAMHEARTBEAT = _descriptor.Descriptor(
  name='StreamHeartbeat',
  full_name='mower.StreamHeartbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='camera', full_name='mower.StreamHeartbeat.camera', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=182,
)


_MOVECONTROLREQ = _descriptor.Descriptor(
  name='MoveControlReq',
  full_name='mower.MoveControlReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='linear_x', full_name='mower.MoveControlReq.linear_x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angular_z', full_name='mower.MoveControlReq.angular_z', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='mower.MoveControlReq.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=256,
)

_PUSHSTREAMREQ.fields_by_name['camera'].enum_type = _CAMERATYPE
_STREAMHEARTBEAT.fields_by_name['camera'].enum_type = _CAMERATYPE
DESCRIPTOR.message_types_by_name['PushStreamReq'] = _PUSHSTREAMREQ
DESCRIPTOR.message_types_by_name['PushStreamRsp'] = _PUSHSTREAMRSP
DESCRIPTOR.message_types_by_name['StreamHeartbeat'] = _STREAMHEARTBEAT
DESCRIPTOR.message_types_by_name['MoveControlReq'] = _MOVECONTROLREQ
DESCRIPTOR.enum_types_by_name['CameraType'] = _CAMERATYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PushStreamReq = _reflection.GeneratedProtocolMessageType('PushStreamReq', (_message.Message,), {
  'DESCRIPTOR' : _PUSHSTREAMREQ,
  '__module__' : 'live_pb2'
  # @@protoc_insertion_point(class_scope:mower.PushStreamReq)
  })
_sym_db.RegisterMessage(PushStreamReq)

PushStreamRsp = _reflection.GeneratedProtocolMessageType('PushStreamRsp', (_message.Message,), {
  'DESCRIPTOR' : _PUSHSTREAMRSP,
  '__module__' : 'live_pb2'
  # @@protoc_insertion_point(class_scope:mower.PushStreamRsp)
  })
_sym_db.RegisterMessage(PushStreamRsp)

StreamHeartbeat = _reflection.GeneratedProtocolMessageType('StreamHeartbeat', (_message.Message,), {
  'DESCRIPTOR' : _STREAMHEARTBEAT,
  '__module__' : 'live_pb2'
  # @@protoc_insertion_point(class_scope:mower.StreamHeartbeat)
  })
_sym_db.RegisterMessage(StreamHeartbeat)

MoveControlReq = _reflection.GeneratedProtocolMessageType('MoveControlReq', (_message.Message,), {
  'DESCRIPTOR' : _MOVECONTROLREQ,
  '__module__' : 'live_pb2'
  # @@protoc_insertion_point(class_scope:mower.MoveControlReq)
  })
_sym_db.RegisterMessage(MoveControlReq)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
