# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlog.proto\x12\x05mower\"$\n\x0fLogUploadURLReq\x12\x11\n\tfile_name\x18\x01 \x01(\t\"\x1e\n\x0fLogUploadURLRsp\x12\x0b\n\x03url\x18\x01 \x01(\t\"#\n\x0eTrackUploadReq\x12\x11\n\tfile_name\x18\x01 \x01(\t\"2\n\x0eTrackUploadRsp\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x13\n\x0bpicture_url\x18\x02 \x01(\tB\x06Z\x04.;pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004.;pb'
  _LOGUPLOADURLREQ._serialized_start=20
  _LOGUPLOADURLREQ._serialized_end=56
  _LOGUPLOADURLRSP._serialized_start=58
  _LOGUPLOADURLRSP._serialized_end=88
  _TRACKUPLOADREQ._serialized_start=90
  _TRACKUPLOADREQ._serialized_end=125
  _TRACKUPLOADRSP._serialized_start=127
  _TRACKUPLOADRSP._serialized_end=177
# @@protoc_insertion_point(module_scope)
