# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='log.proto',
  package='mower',
  syntax='proto3',
  serialized_options=b'Z\004.;pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tlog.proto\x12\x05mower\"$\n\x0fLogUploadURLReq\x12\x11\n\tfile_name\x18\x01 \x01(\t\"\x1e\n\x0fLogUploadURLRsp\x12\x0b\n\x03url\x18\x01 \x01(\t\"#\n\x0eTrackUploadReq\x12\x11\n\tfile_name\x18\x01 \x01(\t\"2\n\x0eTrackUploadRsp\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x13\n\x0bpicture_url\x18\x02 \x01(\tB\x06Z\x04.;pbb\x06proto3'
)




_LOGUPLOADURLREQ = _descriptor.Descriptor(
  name='LogUploadURLReq',
  full_name='mower.LogUploadURLReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_name', full_name='mower.LogUploadURLReq.file_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=56,
)


_LOGUPLOADURLRSP = _descriptor.Descriptor(
  name='LogUploadURLRsp',
  full_name='mower.LogUploadURLRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='mower.LogUploadURLRsp.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=88,
)


_TRACKUPLOADREQ = _descriptor.Descriptor(
  name='TrackUploadReq',
  full_name='mower.TrackUploadReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_name', full_name='mower.TrackUploadReq.file_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=125,
)


_TRACKUPLOADRSP = _descriptor.Descriptor(
  name='TrackUploadRsp',
  full_name='mower.TrackUploadRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='mower.TrackUploadRsp.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='picture_url', full_name='mower.TrackUploadRsp.picture_url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=177,
)

DESCRIPTOR.message_types_by_name['LogUploadURLReq'] = _LOGUPLOADURLREQ
DESCRIPTOR.message_types_by_name['LogUploadURLRsp'] = _LOGUPLOADURLRSP
DESCRIPTOR.message_types_by_name['TrackUploadReq'] = _TRACKUPLOADREQ
DESCRIPTOR.message_types_by_name['TrackUploadRsp'] = _TRACKUPLOADRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LogUploadURLReq = _reflection.GeneratedProtocolMessageType('LogUploadURLReq', (_message.Message,), {
  'DESCRIPTOR' : _LOGUPLOADURLREQ,
  '__module__' : 'log_pb2'
  # @@protoc_insertion_point(class_scope:mower.LogUploadURLReq)
  })
_sym_db.RegisterMessage(LogUploadURLReq)

LogUploadURLRsp = _reflection.GeneratedProtocolMessageType('LogUploadURLRsp', (_message.Message,), {
  'DESCRIPTOR' : _LOGUPLOADURLRSP,
  '__module__' : 'log_pb2'
  # @@protoc_insertion_point(class_scope:mower.LogUploadURLRsp)
  })
_sym_db.RegisterMessage(LogUploadURLRsp)

TrackUploadReq = _reflection.GeneratedProtocolMessageType('TrackUploadReq', (_message.Message,), {
  'DESCRIPTOR' : _TRACKUPLOADREQ,
  '__module__' : 'log_pb2'
  # @@protoc_insertion_point(class_scope:mower.TrackUploadReq)
  })
_sym_db.RegisterMessage(TrackUploadReq)

TrackUploadRsp = _reflection.GeneratedProtocolMessageType('TrackUploadRsp', (_message.Message,), {
  'DESCRIPTOR' : _TRACKUPLOADRSP,
  '__module__' : 'log_pb2'
  # @@protoc_insertion_point(class_scope:mower.TrackUploadRsp)
  })
_sym_db.RegisterMessage(TrackUploadRsp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
