# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmonitor.proto\x12\rmower.monitor\"$\n\x05Usage\x12\x0b\n\x03\x63pu\x18\x01 \x01(\x02\x12\x0e\n\x06memory\x18\x02 \x01(\x02\"]\n\x0bProcessInfo\x12\'\n\x07process\x18\x01 \x01(\x0e\x32\x16.mower.monitor.Process\x12\x0e\n\x06uptime\x18\x02 \x01(\x03\x12\x15\n\rrestart_count\x18\x03 \x01(\x05\"g\n\x0eProcessMonitor\x12\x30\n\x0cprocess_info\x18\x01 \x01(\x0b\x32\x1a.mower.monitor.ProcessInfo\x12#\n\x05usage\x18\x02 \x01(\x0b\x32\x14.mower.monitor.Usage\"m\n\x07Monitor\x12*\n\x0csystem_usage\x18\x01 \x01(\x0b\x32\x14.mower.monitor.Usage\x12\x36\n\x0fprocess_monitor\x18\x03 \x03(\x0b\x32\x1d.mower.monitor.ProcessMonitor*\xbc\x01\n\x07Process\x12\x17\n\x13PROCESS_UNSPECIFIED\x10\x00\x12\x16\n\x12PROCESS_MOWER_BASE\x10\x01\x12\x1c\n\x18PROCESS_MOWER_GPS_DRIVER\x10\x02\x12\x18\n\x14PROCESS_BASE_CAMERAS\x10\x03\x12\x14\n\x10PROCESS_BASE_BLE\x10\x04\x12\x12\n\x0ePROCESS_AS_VIO\x10\x05\x12\x1e\n\x1aPROCESS_MOWER_LOGIC_MASTER\x10\x06\x42\x06Z\x04.;pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monitor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004.;pb'
  _PROCESS._serialized_start=382
  _PROCESS._serialized_end=570
  _USAGE._serialized_start=32
  _USAGE._serialized_end=68
  _PROCESSINFO._serialized_start=70
  _PROCESSINFO._serialized_end=163
  _PROCESSMONITOR._serialized_start=165
  _PROCESSMONITOR._serialized_end=268
  _MONITOR._serialized_start=270
  _MONITOR._serialized_end=379
# @@protoc_insertion_point(module_scope)
