# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='monitor.proto',
  package='mower.monitor',
  syntax='proto3',
  serialized_options=b'Z\004.;pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmonitor.proto\x12\rmower.monitor\"$\n\x05Usage\x12\x0b\n\x03\x63pu\x18\x01 \x01(\x02\x12\x0e\n\x06memory\x18\x02 \x01(\x02\"]\n\x0bProcessInfo\x12\'\n\x07process\x18\x01 \x01(\x0e\x32\x16.mower.monitor.Process\x12\x0e\n\x06uptime\x18\x02 \x01(\x03\x12\x15\n\rrestart_count\x18\x03 \x01(\x05\"g\n\x0eProcessMonitor\x12\x30\n\x0cprocess_info\x18\x01 \x01(\x0b\x32\x1a.mower.monitor.ProcessInfo\x12#\n\x05usage\x18\x02 \x01(\x0b\x32\x14.mower.monitor.Usage\"m\n\x07Monitor\x12*\n\x0csystem_usage\x18\x01 \x01(\x0b\x32\x14.mower.monitor.Usage\x12\x36\n\x0fprocess_monitor\x18\x03 \x03(\x0b\x32\x1d.mower.monitor.ProcessMonitor*\xbc\x01\n\x07Process\x12\x17\n\x13PROCESS_UNSPECIFIED\x10\x00\x12\x16\n\x12PROCESS_MOWER_BASE\x10\x01\x12\x1c\n\x18PROCESS_MOWER_GPS_DRIVER\x10\x02\x12\x18\n\x14PROCESS_BASE_CAMERAS\x10\x03\x12\x14\n\x10PROCESS_BASE_BLE\x10\x04\x12\x12\n\x0ePROCESS_AS_VIO\x10\x05\x12\x1e\n\x1aPROCESS_MOWER_LOGIC_MASTER\x10\x06\x42\x06Z\x04.;pbb\x06proto3'
)

_PROCESS = _descriptor.EnumDescriptor(
  name='Process',
  full_name='mower.monitor.Process',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PROCESS_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROCESS_MOWER_BASE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROCESS_MOWER_GPS_DRIVER', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROCESS_BASE_CAMERAS', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROCESS_BASE_BLE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROCESS_AS_VIO', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROCESS_MOWER_LOGIC_MASTER', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=382,
  serialized_end=570,
)
_sym_db.RegisterEnumDescriptor(_PROCESS)

Process = enum_type_wrapper.EnumTypeWrapper(_PROCESS)
PROCESS_UNSPECIFIED = 0
PROCESS_MOWER_BASE = 1
PROCESS_MOWER_GPS_DRIVER = 2
PROCESS_BASE_CAMERAS = 3
PROCESS_BASE_BLE = 4
PROCESS_AS_VIO = 5
PROCESS_MOWER_LOGIC_MASTER = 6



_USAGE = _descriptor.Descriptor(
  name='Usage',
  full_name='mower.monitor.Usage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpu', full_name='mower.monitor.Usage.cpu', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='memory', full_name='mower.monitor.Usage.memory', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=68,
)


_PROCESSINFO = _descriptor.Descriptor(
  name='ProcessInfo',
  full_name='mower.monitor.ProcessInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='process', full_name='mower.monitor.ProcessInfo.process', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uptime', full_name='mower.monitor.ProcessInfo.uptime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='restart_count', full_name='mower.monitor.ProcessInfo.restart_count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=163,
)


_PROCESSMONITOR = _descriptor.Descriptor(
  name='ProcessMonitor',
  full_name='mower.monitor.ProcessMonitor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='process_info', full_name='mower.monitor.ProcessMonitor.process_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='usage', full_name='mower.monitor.ProcessMonitor.usage', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=268,
)


_MONITOR = _descriptor.Descriptor(
  name='Monitor',
  full_name='mower.monitor.Monitor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='system_usage', full_name='mower.monitor.Monitor.system_usage', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='process_monitor', full_name='mower.monitor.Monitor.process_monitor', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=379,
)

_PROCESSINFO.fields_by_name['process'].enum_type = _PROCESS
_PROCESSMONITOR.fields_by_name['process_info'].message_type = _PROCESSINFO
_PROCESSMONITOR.fields_by_name['usage'].message_type = _USAGE
_MONITOR.fields_by_name['system_usage'].message_type = _USAGE
_MONITOR.fields_by_name['process_monitor'].message_type = _PROCESSMONITOR
DESCRIPTOR.message_types_by_name['Usage'] = _USAGE
DESCRIPTOR.message_types_by_name['ProcessInfo'] = _PROCESSINFO
DESCRIPTOR.message_types_by_name['ProcessMonitor'] = _PROCESSMONITOR
DESCRIPTOR.message_types_by_name['Monitor'] = _MONITOR
DESCRIPTOR.enum_types_by_name['Process'] = _PROCESS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Usage = _reflection.GeneratedProtocolMessageType('Usage', (_message.Message,), {
  'DESCRIPTOR' : _USAGE,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:mower.monitor.Usage)
  })
_sym_db.RegisterMessage(Usage)

ProcessInfo = _reflection.GeneratedProtocolMessageType('ProcessInfo', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSINFO,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:mower.monitor.ProcessInfo)
  })
_sym_db.RegisterMessage(ProcessInfo)

ProcessMonitor = _reflection.GeneratedProtocolMessageType('ProcessMonitor', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSMONITOR,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:mower.monitor.ProcessMonitor)
  })
_sym_db.RegisterMessage(ProcessMonitor)

Monitor = _reflection.GeneratedProtocolMessageType('Monitor', (_message.Message,), {
  'DESCRIPTOR' : _MONITOR,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:mower.monitor.Monitor)
  })
_sym_db.RegisterMessage(Monitor)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
