# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: security.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='security.proto',
  package='mower',
  syntax='proto3',
  serialized_options=b'Z\004.;pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0esecurity.proto\x12\x05mower\"\x0f\n\rLockDeviceReq\"\x0f\n\rLockDeviceRsp\"\x11\n\x0fUnLockDeviceReq\"\x11\n\x0fUnLockDeviceRspB\x06Z\x04.;pbb\x06proto3'
)




_LOCKDEVICEREQ = _descriptor.Descriptor(
  name='LockDeviceReq',
  full_name='mower.LockDeviceReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=40,
)


_LOCKDEVICERSP = _descriptor.Descriptor(
  name='LockDeviceRsp',
  full_name='mower.LockDeviceRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=57,
)


_UNLOCKDEVICEREQ = _descriptor.Descriptor(
  name='UnLockDeviceReq',
  full_name='mower.UnLockDeviceReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=76,
)


_UNLOCKDEVICERSP = _descriptor.Descriptor(
  name='UnLockDeviceRsp',
  full_name='mower.UnLockDeviceRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['LockDeviceReq'] = _LOCKDEVICEREQ
DESCRIPTOR.message_types_by_name['LockDeviceRsp'] = _LOCKDEVICERSP
DESCRIPTOR.message_types_by_name['UnLockDeviceReq'] = _UNLOCKDEVICEREQ
DESCRIPTOR.message_types_by_name['UnLockDeviceRsp'] = _UNLOCKDEVICERSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LockDeviceReq = _reflection.GeneratedProtocolMessageType('LockDeviceReq', (_message.Message,), {
  'DESCRIPTOR' : _LOCKDEVICEREQ,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:mower.LockDeviceReq)
  })
_sym_db.RegisterMessage(LockDeviceReq)

LockDeviceRsp = _reflection.GeneratedProtocolMessageType('LockDeviceRsp', (_message.Message,), {
  'DESCRIPTOR' : _LOCKDEVICERSP,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:mower.LockDeviceRsp)
  })
_sym_db.RegisterMessage(LockDeviceRsp)

UnLockDeviceReq = _reflection.GeneratedProtocolMessageType('UnLockDeviceReq', (_message.Message,), {
  'DESCRIPTOR' : _UNLOCKDEVICEREQ,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:mower.UnLockDeviceReq)
  })
_sym_db.RegisterMessage(UnLockDeviceReq)

UnLockDeviceRsp = _reflection.GeneratedProtocolMessageType('UnLockDeviceRsp', (_message.Message,), {
  'DESCRIPTOR' : _UNLOCKDEVICERSP,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:mower.UnLockDeviceRsp)
  })
_sym_db.RegisterMessage(UnLockDeviceRsp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
