# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: security.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esecurity.proto\x12\x05mower\"\x0f\n\rLockDeviceReq\"\x0f\n\rLockDeviceRsp\"\x11\n\x0fUnLockDeviceReq\"\x11\n\x0fUnLockDeviceRspB\x06Z\x04.;pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'security_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004.;pb'
  _LOCKDEVICEREQ._serialized_start=25
  _LOCKDEVICEREQ._serialized_end=40
  _LOCKDEVICERSP._serialized_start=42
  _LOCKDEVICERSP._serialized_end=57
  _UNLOCKDEVICEREQ._serialized_start=59
  _UNLOCKDEVICEREQ._serialized_end=76
  _UNLOCKDEVICERSP._serialized_start=78
  _UNLOCKDEVICERSP._serialized_end=95
# @@protoc_insertion_point(module_scope)
