# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teleop.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='teleop.proto',
  package='mower.teleop',
  syntax='proto3',
  serialized_options=b'Z\004.;pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cteleop.proto\x12\x0cmower.teleop\x1a\x0c\x63ommon.proto\"\xc8\x02\n\nTeleopMode\x12+\n\x04type\x18\x01 \x01(\x0e\x32\x1d.mower.teleop.TeleopMode.Type\x12/\n\x06\x63utter\x18\x02 \x01(\x0e\x32\x1f.mower.teleop.TeleopMode.Cutter\x12\x15\n\rcutter_height\x18\x04 \x01(\x05\x12/\n\x06result\x18\x03 \x01(\x0e\x32\x1f.mower.teleop.TeleopMode.Result\",\n\x04Type\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\t\n\x05START\x10\x01\x12\x08\n\x04STOP\x10\x02\"C\n\x06\x43utter\x12\x16\n\x12\x43UTTER_UNSPECIFIED\x10\x00\x12\x10\n\x0c\x43UTTER_START\x10\x01\x12\x0f\n\x0b\x43UTTER_STOP\x10\x02\"!\n\x06Result\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x42\x06Z\x04.;pbb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])



_TELEOPMODE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='mower.teleop.TeleopMode.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='START', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=225,
  serialized_end=269,
)
_sym_db.RegisterEnumDescriptor(_TELEOPMODE_TYPE)

_TELEOPMODE_CUTTER = _descriptor.EnumDescriptor(
  name='Cutter',
  full_name='mower.teleop.TeleopMode.Cutter',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CUTTER_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CUTTER_START', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CUTTER_STOP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=271,
  serialized_end=338,
)
_sym_db.RegisterEnumDescriptor(_TELEOPMODE_CUTTER)

_TELEOPMODE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='mower.teleop.TeleopMode.Result',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=340,
  serialized_end=373,
)
_sym_db.RegisterEnumDescriptor(_TELEOPMODE_RESULT)


_TELEOPMODE = _descriptor.Descriptor(
  name='TeleopMode',
  full_name='mower.teleop.TeleopMode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='mower.teleop.TeleopMode.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cutter', full_name='mower.teleop.TeleopMode.cutter', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cutter_height', full_name='mower.teleop.TeleopMode.cutter_height', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='mower.teleop.TeleopMode.result', index=3,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TELEOPMODE_TYPE,
    _TELEOPMODE_CUTTER,
    _TELEOPMODE_RESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=373,
)

_TELEOPMODE.fields_by_name['type'].enum_type = _TELEOPMODE_TYPE
_TELEOPMODE.fields_by_name['cutter'].enum_type = _TELEOPMODE_CUTTER
_TELEOPMODE.fields_by_name['result'].enum_type = _TELEOPMODE_RESULT
_TELEOPMODE_TYPE.containing_type = _TELEOPMODE
_TELEOPMODE_CUTTER.containing_type = _TELEOPMODE
_TELEOPMODE_RESULT.containing_type = _TELEOPMODE
DESCRIPTOR.message_types_by_name['TeleopMode'] = _TELEOPMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TeleopMode = _reflection.GeneratedProtocolMessageType('TeleopMode', (_message.Message,), {
  'DESCRIPTOR' : _TELEOPMODE,
  '__module__' : 'teleop_pb2'
  # @@protoc_insertion_point(class_scope:mower.teleop.TeleopMode)
  })
_sym_db.RegisterMessage(TeleopMode)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
