# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teleop.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cteleop.proto\x12\x0cmower.teleop\x1a\x0c\x63ommon.proto\"\xc8\x02\n\nTeleopMode\x12+\n\x04type\x18\x01 \x01(\x0e\x32\x1d.mower.teleop.TeleopMode.Type\x12/\n\x06\x63utter\x18\x02 \x01(\x0e\x32\x1f.mower.teleop.TeleopMode.Cutter\x12\x15\n\rcutter_height\x18\x04 \x01(\x05\x12/\n\x06result\x18\x03 \x01(\x0e\x32\x1f.mower.teleop.TeleopMode.Result\",\n\x04Type\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\t\n\x05START\x10\x01\x12\x08\n\x04STOP\x10\x02\"C\n\x06\x43utter\x12\x16\n\x12\x43UTTER_UNSPECIFIED\x10\x00\x12\x10\n\x0c\x43UTTER_START\x10\x01\x12\x0f\n\x0b\x43UTTER_STOP\x10\x02\"!\n\x06Result\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x42\x06Z\x04.;pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'teleop_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004.;pb'
  _TELEOPMODE._serialized_start=45
  _TELEOPMODE._serialized_end=373
  _TELEOPMODE_TYPE._serialized_start=225
  _TELEOPMODE_TYPE._serialized_end=269
  _TELEOPMODE_CUTTER._serialized_start=271
  _TELEOPMODE_CUTTER._serialized_end=338
  _TELEOPMODE_RESULT._serialized_start=340
  _TELEOPMODE_RESULT._serialized_end=373
# @@protoc_insertion_point(module_scope)
