# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: upgrade_mcu.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11upgrade_mcu.proto\x12\x11mower.upgrade.mcu\"\xef\x02\n\x13UpgradeMCUStatusReq\x12\x10\n\x08progress\x18\x01 \x01(\x05\x12\x39\n\x04step\x18\x02 \x01(\x0e\x32+.mower.upgrade.mcu.UpgradeMCUStatusReq.Step\x12;\n\x05state\x18\x03 \x01(\x0e\x32,.mower.upgrade.mcu.UpgradeMCUStatusReq.State\x12(\n\x04type\x18\x04 \x01(\x0e\x32\x1a.mower.upgrade.mcu.MCUType\x12\x17\n\x0f\x63urrent_version\x18\x05 \x01(\t\x12\x16\n\x0etarget_version\x18\x06 \x01(\t\"H\n\x04Step\x12\x0c\n\x08OTA_IDLE\x10\x00\x12\x0f\n\x0bOTA_PENDING\x10\x01\x12\x10\n\x0cOTA_APPROVED\x10\x02\x12\x0f\n\x0bOTA_INSTALL\x10\x03\")\n\x05State\x12\x07\n\x03ING\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\"\x15\n\x13UpgradeMCUStatusRsp*|\n\x07MCUType\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\x0f\n\x0bTYPE_CUTTER\x10\x01\x12\x0e\n\nTYPE_WHEEL\x10\x02\x12\x10\n\x0cTYPE_BATTERY\x10\x03\x12\x12\n\x0eTYPE_RTK_ROVER\x10\x04\x12\x14\n\x10TYPE_RTK_STATION\x10\x05\x42\x06Z\x04.;pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'upgrade_mcu_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004.;pb'
  _MCUTYPE._serialized_start=433
  _MCUTYPE._serialized_end=557
  _UPGRADEMCUSTATUSREQ._serialized_start=41
  _UPGRADEMCUSTATUSREQ._serialized_end=408
  _UPGRADEMCUSTATUSREQ_STEP._serialized_start=293
  _UPGRADEMCUSTATUSREQ_STEP._serialized_end=365
  _UPGRADEMCUSTATUSREQ_STATE._serialized_start=367
  _UPGRADEMCUSTATUSREQ_STATE._serialized_end=408
  _UPGRADEMCUSTATUSRSP._serialized_start=410
  _UPGRADEMCUSTATUSRSP._serialized_end=431
# @@protoc_insertion_point(module_scope)
