# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: upgrade_mcu.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='upgrade_mcu.proto',
  package='mower.upgrade.mcu',
  syntax='proto3',
  serialized_options=b'Z\004.;pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11upgrade_mcu.proto\x12\x11mower.upgrade.mcu\"\xef\x02\n\x13UpgradeMCUStatusReq\x12\x10\n\x08progress\x18\x01 \x01(\x05\x12\x39\n\x04step\x18\x02 \x01(\x0e\x32+.mower.upgrade.mcu.UpgradeMCUStatusReq.Step\x12;\n\x05state\x18\x03 \x01(\x0e\x32,.mower.upgrade.mcu.UpgradeMCUStatusReq.State\x12(\n\x04type\x18\x04 \x01(\x0e\x32\x1a.mower.upgrade.mcu.MCUType\x12\x17\n\x0f\x63urrent_version\x18\x05 \x01(\t\x12\x16\n\x0etarget_version\x18\x06 \x01(\t\"H\n\x04Step\x12\x0c\n\x08OTA_IDLE\x10\x00\x12\x0f\n\x0bOTA_PENDING\x10\x01\x12\x10\n\x0cOTA_APPROVED\x10\x02\x12\x0f\n\x0bOTA_INSTALL\x10\x03\")\n\x05State\x12\x07\n\x03ING\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\"\x15\n\x13UpgradeMCUStatusRsp*|\n\x07MCUType\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\x0f\n\x0bTYPE_CUTTER\x10\x01\x12\x0e\n\nTYPE_WHEEL\x10\x02\x12\x10\n\x0cTYPE_BATTERY\x10\x03\x12\x12\n\x0eTYPE_RTK_ROVER\x10\x04\x12\x14\n\x10TYPE_RTK_STATION\x10\x05\x42\x06Z\x04.;pbb\x06proto3'
)

_MCUTYPE = _descriptor.EnumDescriptor(
  name='MCUType',
  full_name='mower.upgrade.mcu.MCUType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TYPE_CUTTER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TYPE_WHEEL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TYPE_BATTERY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TYPE_RTK_ROVER', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TYPE_RTK_STATION', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=433,
  serialized_end=557,
)
_sym_db.RegisterEnumDescriptor(_MCUTYPE)

MCUType = enum_type_wrapper.EnumTypeWrapper(_MCUTYPE)
TYPE_UNSPECIFIED = 0
TYPE_CUTTER = 1
TYPE_WHEEL = 2
TYPE_BATTERY = 3
TYPE_RTK_ROVER = 4
TYPE_RTK_STATION = 5


_UPGRADEMCUSTATUSREQ_STEP = _descriptor.EnumDescriptor(
  name='Step',
  full_name='mower.upgrade.mcu.UpgradeMCUStatusReq.Step',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OTA_IDLE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OTA_PENDING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OTA_APPROVED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OTA_INSTALL', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=293,
  serialized_end=365,
)
_sym_db.RegisterEnumDescriptor(_UPGRADEMCUSTATUSREQ_STEP)

_UPGRADEMCUSTATUSREQ_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='mower.upgrade.mcu.UpgradeMCUStatusReq.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ING', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=367,
  serialized_end=408,
)
_sym_db.RegisterEnumDescriptor(_UPGRADEMCUSTATUSREQ_STATE)


_UPGRADEMCUSTATUSREQ = _descriptor.Descriptor(
  name='UpgradeMCUStatusReq',
  full_name='mower.upgrade.mcu.UpgradeMCUStatusReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='progress', full_name='mower.upgrade.mcu.UpgradeMCUStatusReq.progress', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='step', full_name='mower.upgrade.mcu.UpgradeMCUStatusReq.step', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='mower.upgrade.mcu.UpgradeMCUStatusReq.state', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='mower.upgrade.mcu.UpgradeMCUStatusReq.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_version', full_name='mower.upgrade.mcu.UpgradeMCUStatusReq.current_version', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_version', full_name='mower.upgrade.mcu.UpgradeMCUStatusReq.target_version', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _UPGRADEMCUSTATUSREQ_STEP,
    _UPGRADEMCUSTATUSREQ_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=408,
)


_UPGRADEMCUSTATUSRSP = _descriptor.Descriptor(
  name='UpgradeMCUStatusRsp',
  full_name='mower.upgrade.mcu.UpgradeMCUStatusRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=431,
)

_UPGRADEMCUSTATUSREQ.fields_by_name['step'].enum_type = _UPGRADEMCUSTATUSREQ_STEP
_UPGRADEMCUSTATUSREQ.fields_by_name['state'].enum_type = _UPGRADEMCUSTATUSREQ_STATE
_UPGRADEMCUSTATUSREQ.fields_by_name['type'].enum_type = _MCUTYPE
_UPGRADEMCUSTATUSREQ_STEP.containing_type = _UPGRADEMCUSTATUSREQ
_UPGRADEMCUSTATUSREQ_STATE.containing_type = _UPGRADEMCUSTATUSREQ
DESCRIPTOR.message_types_by_name['UpgradeMCUStatusReq'] = _UPGRADEMCUSTATUSREQ
DESCRIPTOR.message_types_by_name['UpgradeMCUStatusRsp'] = _UPGRADEMCUSTATUSRSP
DESCRIPTOR.enum_types_by_name['MCUType'] = _MCUTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpgradeMCUStatusReq = _reflection.GeneratedProtocolMessageType('UpgradeMCUStatusReq', (_message.Message,), {
  'DESCRIPTOR' : _UPGRADEMCUSTATUSREQ,
  '__module__' : 'upgrade_mcu_pb2'
  # @@protoc_insertion_point(class_scope:mower.upgrade.mcu.UpgradeMCUStatusReq)
  })
_sym_db.RegisterMessage(UpgradeMCUStatusReq)

UpgradeMCUStatusRsp = _reflection.GeneratedProtocolMessageType('UpgradeMCUStatusRsp', (_message.Message,), {
  'DESCRIPTOR' : _UPGRADEMCUSTATUSRSP,
  '__module__' : 'upgrade_mcu_pb2'
  # @@protoc_insertion_point(class_scope:mower.upgrade.mcu.UpgradeMCUStatusRsp)
  })
_sym_db.RegisterMessage(UpgradeMCUStatusRsp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
