# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: upgrade.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='upgrade.proto',
  package='mower',
  syntax='proto3',
  serialized_options=b'Z\004.;pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rupgrade.proto\x12\x05mower\"o\n\nUpgradeReq\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x19\n\x0c\x66irmware_url\x18\x02 \x01(\tR\x03url\x12\r\n\x05\x66orce\x18\x03 \x01(\x08\x12\x0b\n\x03md5\x18\x04 \x01(\t\x12\x19\n\x11upgrade_idle_time\x18\x05 \x01(\x08\"|\n\nUpgradeRsp\x12/\n\nerror_code\x18\x01 \x01(\x0e\x32\x1b.mower.UpgradeRsp.ErrorCode\x12\x0b\n\x03msg\x18\x02 \x01(\t\"0\n\tErrorCode\x12\x11\n\rError_Success\x10\x00\x12\x10\n\x0c\x45rror_Failed\x10\x01\"\x12\n\x10UpgradeStatusReq\"\x84\x02\n\x10UpgradeStatusRsp\x12\x10\n\x08progress\x18\x01 \x01(\x05\x12*\n\x04step\x18\x02 \x01(\x0e\x32\x1c.mower.UpgradeStatusRsp.Step\x12,\n\x05state\x18\x03 \x01(\x0e\x32\x1d.mower.UpgradeStatusRsp.State\x12\x0f\n\x07version\x18\x04 \x01(\t\"H\n\x04Step\x12\x0c\n\x08OTA_IDLE\x10\x00\x12\x10\n\x0cOTA_DOWNLOAD\x10\x01\x12\x0f\n\x0bOTA_EXTRACT\x10\x02\x12\x0f\n\x0bOTA_INSTALL\x10\x03\")\n\x05State\x12\x07\n\x03ING\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\"q\n\x0fVoiceUpgradeReq\x12\x16\n\x0evoice_language\x18\x01 \x01(\t\x12\x15\n\rvoice_version\x18\x02 \x01(\t\x12\x13\n\x0bpackage_url\x18\x03 \x01(\t\x12\x0b\n\x03md5\x18\x04 \x01(\t\x12\r\n\x05\x66orce\x18\x05 \x01(\x08\"\x86\x01\n\x0fVoiceUpgradeRsp\x12\x34\n\nerror_code\x18\x01 \x01(\x0e\x32 .mower.VoiceUpgradeRsp.ErrorCode\x12\x0b\n\x03msg\x18\x02 \x01(\t\"0\n\tErrorCode\x12\x11\n\rError_Success\x10\x00\x12\x10\n\x0c\x45rror_Failed\x10\x01\"+\n\x10LatestVersionReq\x12\x17\n\x0f\x63urrent_version\x18\x01 \x01(\t\"U\n\x10LatestVersionRsp\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x14\n\x0c\x66irmware_url\x18\x02 \x01(\t\x12\r\n\x05\x66orce\x18\x03 \x01(\x08\x12\x0b\n\x03md5\x18\x04 \x01(\tB\x06Z\x04.;pbb\x06proto3'
)



_UPGRADERSP_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='mower.UpgradeRsp.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Error_Success', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Error_Failed', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=213,
  serialized_end=261,
)
_sym_db.RegisterEnumDescriptor(_UPGRADERSP_ERRORCODE)

_UPGRADESTATUSRSP_STEP = _descriptor.EnumDescriptor(
  name='Step',
  full_name='mower.UpgradeStatusRsp.Step',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OTA_IDLE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OTA_DOWNLOAD', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OTA_EXTRACT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OTA_INSTALL', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=429,
  serialized_end=501,
)
_sym_db.RegisterEnumDescriptor(_UPGRADESTATUSRSP_STEP)

_UPGRADESTATUSRSP_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='mower.UpgradeStatusRsp.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ING', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=503,
  serialized_end=544,
)
_sym_db.RegisterEnumDescriptor(_UPGRADESTATUSRSP_STATE)

_VOICEUPGRADERSP_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='mower.VoiceUpgradeRsp.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Error_Success', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Error_Failed', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=213,
  serialized_end=261,
)
_sym_db.RegisterEnumDescriptor(_VOICEUPGRADERSP_ERRORCODE)


_UPGRADEREQ = _descriptor.Descriptor(
  name='UpgradeReq',
  full_name='mower.UpgradeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='mower.UpgradeReq.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='firmware_url', full_name='mower.UpgradeReq.firmware_url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='url', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='force', full_name='mower.UpgradeReq.force', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='md5', full_name='mower.UpgradeReq.md5', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upgrade_idle_time', full_name='mower.UpgradeReq.upgrade_idle_time', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=135,
)


_UPGRADERSP = _descriptor.Descriptor(
  name='UpgradeRsp',
  full_name='mower.UpgradeRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='mower.UpgradeRsp.error_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='mower.UpgradeRsp.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _UPGRADERSP_ERRORCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=261,
)


_UPGRADESTATUSREQ = _descriptor.Descriptor(
  name='UpgradeStatusReq',
  full_name='mower.UpgradeStatusReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=281,
)


_UPGRADESTATUSRSP = _descriptor.Descriptor(
  name='UpgradeStatusRsp',
  full_name='mower.UpgradeStatusRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='progress', full_name='mower.UpgradeStatusRsp.progress', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='step', full_name='mower.UpgradeStatusRsp.step', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='mower.UpgradeStatusRsp.state', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='mower.UpgradeStatusRsp.version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _UPGRADESTATUSRSP_STEP,
    _UPGRADESTATUSRSP_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=544,
)


_VOICEUPGRADEREQ = _descriptor.Descriptor(
  name='VoiceUpgradeReq',
  full_name='mower.VoiceUpgradeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='voice_language', full_name='mower.VoiceUpgradeReq.voice_language', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='voice_version', full_name='mower.VoiceUpgradeReq.voice_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='package_url', full_name='mower.VoiceUpgradeReq.package_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='md5', full_name='mower.VoiceUpgradeReq.md5', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='force', full_name='mower.VoiceUpgradeReq.force', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=546,
  serialized_end=659,
)


_VOICEUPGRADERSP = _descriptor.Descriptor(
  name='VoiceUpgradeRsp',
  full_name='mower.VoiceUpgradeRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='mower.VoiceUpgradeRsp.error_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='mower.VoiceUpgradeRsp.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VOICEUPGRADERSP_ERRORCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=662,
  serialized_end=796,
)


_LATESTVERSIONREQ = _descriptor.Descriptor(
  name='LatestVersionReq',
  full_name='mower.LatestVersionReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_version', full_name='mower.LatestVersionReq.current_version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=798,
  serialized_end=841,
)


_LATESTVERSIONRSP = _descriptor.Descriptor(
  name='LatestVersionRsp',
  full_name='mower.LatestVersionRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='mower.LatestVersionRsp.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='firmware_url', full_name='mower.LatestVersionRsp.firmware_url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='force', full_name='mower.LatestVersionRsp.force', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='md5', full_name='mower.LatestVersionRsp.md5', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=843,
  serialized_end=928,
)

_UPGRADERSP.fields_by_name['error_code'].enum_type = _UPGRADERSP_ERRORCODE
_UPGRADERSP_ERRORCODE.containing_type = _UPGRADERSP
_UPGRADESTATUSRSP.fields_by_name['step'].enum_type = _UPGRADESTATUSRSP_STEP
_UPGRADESTATUSRSP.fields_by_name['state'].enum_type = _UPGRADESTATUSRSP_STATE
_UPGRADESTATUSRSP_STEP.containing_type = _UPGRADESTATUSRSP
_UPGRADESTATUSRSP_STATE.containing_type = _UPGRADESTATUSRSP
_VOICEUPGRADERSP.fields_by_name['error_code'].enum_type = _VOICEUPGRADERSP_ERRORCODE
_VOICEUPGRADERSP_ERRORCODE.containing_type = _VOICEUPGRADERSP
DESCRIPTOR.message_types_by_name['UpgradeReq'] = _UPGRADEREQ
DESCRIPTOR.message_types_by_name['UpgradeRsp'] = _UPGRADERSP
DESCRIPTOR.message_types_by_name['UpgradeStatusReq'] = _UPGRADESTATUSREQ
DESCRIPTOR.message_types_by_name['UpgradeStatusRsp'] = _UPGRADESTATUSRSP
DESCRIPTOR.message_types_by_name['VoiceUpgradeReq'] = _VOICEUPGRADEREQ
DESCRIPTOR.message_types_by_name['VoiceUpgradeRsp'] = _VOICEUPGRADERSP
DESCRIPTOR.message_types_by_name['LatestVersionReq'] = _LATESTVERSIONREQ
DESCRIPTOR.message_types_by_name['LatestVersionRsp'] = _LATESTVERSIONRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpgradeReq = _reflection.GeneratedProtocolMessageType('UpgradeReq', (_message.Message,), {
  'DESCRIPTOR' : _UPGRADEREQ,
  '__module__' : 'upgrade_pb2'
  # @@protoc_insertion_point(class_scope:mower.UpgradeReq)
  })
_sym_db.RegisterMessage(UpgradeReq)

UpgradeRsp = _reflection.GeneratedProtocolMessageType('UpgradeRsp', (_message.Message,), {
  'DESCRIPTOR' : _UPGRADERSP,
  '__module__' : 'upgrade_pb2'
  # @@protoc_insertion_point(class_scope:mower.UpgradeRsp)
  })
_sym_db.RegisterMessage(UpgradeRsp)

UpgradeStatusReq = _reflection.GeneratedProtocolMessageType('UpgradeStatusReq', (_message.Message,), {
  'DESCRIPTOR' : _UPGRADESTATUSREQ,
  '__module__' : 'upgrade_pb2'
  # @@protoc_insertion_point(class_scope:mower.UpgradeStatusReq)
  })
_sym_db.RegisterMessage(UpgradeStatusReq)

UpgradeStatusRsp = _reflection.GeneratedProtocolMessageType('UpgradeStatusRsp', (_message.Message,), {
  'DESCRIPTOR' : _UPGRADESTATUSRSP,
  '__module__' : 'upgrade_pb2'
  # @@protoc_insertion_point(class_scope:mower.UpgradeStatusRsp)
  })
_sym_db.RegisterMessage(UpgradeStatusRsp)

VoiceUpgradeReq = _reflection.GeneratedProtocolMessageType('VoiceUpgradeReq', (_message.Message,), {
  'DESCRIPTOR' : _VOICEUPGRADEREQ,
  '__module__' : 'upgrade_pb2'
  # @@protoc_insertion_point(class_scope:mower.VoiceUpgradeReq)
  })
_sym_db.RegisterMessage(VoiceUpgradeReq)

VoiceUpgradeRsp = _reflection.GeneratedProtocolMessageType('VoiceUpgradeRsp', (_message.Message,), {
  'DESCRIPTOR' : _VOICEUPGRADERSP,
  '__module__' : 'upgrade_pb2'
  # @@protoc_insertion_point(class_scope:mower.VoiceUpgradeRsp)
  })
_sym_db.RegisterMessage(VoiceUpgradeRsp)

LatestVersionReq = _reflection.GeneratedProtocolMessageType('LatestVersionReq', (_message.Message,), {
  'DESCRIPTOR' : _LATESTVERSIONREQ,
  '__module__' : 'upgrade_pb2'
  # @@protoc_insertion_point(class_scope:mower.LatestVersionReq)
  })
_sym_db.RegisterMessage(LatestVersionReq)

LatestVersionRsp = _reflection.GeneratedProtocolMessageType('LatestVersionRsp', (_message.Message,), {
  'DESCRIPTOR' : _LATESTVERSIONRSP,
  '__module__' : 'upgrade_pb2'
  # @@protoc_insertion_point(class_scope:mower.LatestVersionRsp)
  })
_sym_db.RegisterMessage(LatestVersionRsp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
