# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: upgrade.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rupgrade.proto\x12\x05mower\"o\n\nUpgradeReq\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x19\n\x0c\x66irmware_url\x18\x02 \x01(\tR\x03url\x12\r\n\x05\x66orce\x18\x03 \x01(\x08\x12\x0b\n\x03md5\x18\x04 \x01(\t\x12\x19\n\x11upgrade_idle_time\x18\x05 \x01(\x08\"|\n\nUpgradeRsp\x12/\n\nerror_code\x18\x01 \x01(\x0e\x32\x1b.mower.UpgradeRsp.ErrorCode\x12\x0b\n\x03msg\x18\x02 \x01(\t\"0\n\tErrorCode\x12\x11\n\rError_Success\x10\x00\x12\x10\n\x0c\x45rror_Failed\x10\x01\"\x12\n\x10UpgradeStatusReq\"\x84\x02\n\x10UpgradeStatusRsp\x12\x10\n\x08progress\x18\x01 \x01(\x05\x12*\n\x04step\x18\x02 \x01(\x0e\x32\x1c.mower.UpgradeStatusRsp.Step\x12,\n\x05state\x18\x03 \x01(\x0e\x32\x1d.mower.UpgradeStatusRsp.State\x12\x0f\n\x07version\x18\x04 \x01(\t\"H\n\x04Step\x12\x0c\n\x08OTA_IDLE\x10\x00\x12\x10\n\x0cOTA_DOWNLOAD\x10\x01\x12\x0f\n\x0bOTA_EXTRACT\x10\x02\x12\x0f\n\x0bOTA_INSTALL\x10\x03\")\n\x05State\x12\x07\n\x03ING\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\"q\n\x0fVoiceUpgradeReq\x12\x16\n\x0evoice_language\x18\x01 \x01(\t\x12\x15\n\rvoice_version\x18\x02 \x01(\t\x12\x13\n\x0bpackage_url\x18\x03 \x01(\t\x12\x0b\n\x03md5\x18\x04 \x01(\t\x12\r\n\x05\x66orce\x18\x05 \x01(\x08\"\x86\x01\n\x0fVoiceUpgradeRsp\x12\x34\n\nerror_code\x18\x01 \x01(\x0e\x32 .mower.VoiceUpgradeRsp.ErrorCode\x12\x0b\n\x03msg\x18\x02 \x01(\t\"0\n\tErrorCode\x12\x11\n\rError_Success\x10\x00\x12\x10\n\x0c\x45rror_Failed\x10\x01\"+\n\x10LatestVersionReq\x12\x17\n\x0f\x63urrent_version\x18\x01 \x01(\t\"U\n\x10LatestVersionRsp\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x14\n\x0c\x66irmware_url\x18\x02 \x01(\t\x12\r\n\x05\x66orce\x18\x03 \x01(\x08\x12\x0b\n\x03md5\x18\x04 \x01(\tB\x06Z\x04.;pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'upgrade_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004.;pb'
  _UPGRADEREQ._serialized_start=24
  _UPGRADEREQ._serialized_end=135
  _UPGRADERSP._serialized_start=137
  _UPGRADERSP._serialized_end=261
  _UPGRADERSP_ERRORCODE._serialized_start=213
  _UPGRADERSP_ERRORCODE._serialized_end=261
  _UPGRADESTATUSREQ._serialized_start=263
  _UPGRADESTATUSREQ._serialized_end=281
  _UPGRADESTATUSRSP._serialized_start=284
  _UPGRADESTATUSRSP._serialized_end=544
  _UPGRADESTATUSRSP_STEP._serialized_start=429
  _UPGRADESTATUSRSP_STEP._serialized_end=501
  _UPGRADESTATUSRSP_STATE._serialized_start=503
  _UPGRADESTATUSRSP_STATE._serialized_end=544
  _VOICEUPGRADEREQ._serialized_start=546
  _VOICEUPGRADEREQ._serialized_end=659
  _VOICEUPGRADERSP._serialized_start=662
  _VOICEUPGRADERSP._serialized_end=796
  _VOICEUPGRADERSP_ERRORCODE._serialized_start=213
  _VOICEUPGRADERSP_ERRORCODE._serialized_end=261
  _LATESTVERSIONREQ._serialized_start=798
  _LATESTVERSIONREQ._serialized_end=841
  _LATESTVERSIONRSP._serialized_start=843
  _LATESTVERSIONRSP._serialized_end=928
# @@protoc_insertion_point(module_scope)
