# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webshell_agent.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='webshell_agent.proto',
  package='mower',
  syntax='proto3',
  serialized_options=b'Z\004.;pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14webshell_agent.proto\x12\x05mower\"\x13\n\x11WebshellEnableReq\"\x7f\n\x11WebshellEnableRsp\x12\x37\n\x0b\x65rrror_code\x18\x01 \x01(\x0e\x32\".mower.WebshellEnableRsp.ErrorCode\x12\x0b\n\x03msg\x18\x02 \x01(\t\"$\n\tErrorCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\"\x14\n\x12WebshellDisableReq\"\x81\x01\n\x12WebshellDisableRsp\x12\x38\n\x0b\x65rrror_code\x18\x01 \x01(\x0e\x32#.mower.WebshellDisableRsp.ErrorCode\x12\x0b\n\x03msg\x18\x02 \x01(\t\"$\n\tErrorCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x42\x06Z\x04.;pbb\x06proto3'
)



_WEBSHELLENABLERSP_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='mower.WebshellEnableRsp.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=143,
  serialized_end=179,
)
_sym_db.RegisterEnumDescriptor(_WEBSHELLENABLERSP_ERRORCODE)

_WEBSHELLDISABLERSP_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='mower.WebshellDisableRsp.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=143,
  serialized_end=179,
)
_sym_db.RegisterEnumDescriptor(_WEBSHELLDISABLERSP_ERRORCODE)


_WEBSHELLENABLEREQ = _descriptor.Descriptor(
  name='WebshellEnableReq',
  full_name='mower.WebshellEnableReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=50,
)


_WEBSHELLENABLERSP = _descriptor.Descriptor(
  name='WebshellEnableRsp',
  full_name='mower.WebshellEnableRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='errror_code', full_name='mower.WebshellEnableRsp.errror_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='mower.WebshellEnableRsp.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WEBSHELLENABLERSP_ERRORCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=179,
)


_WEBSHELLDISABLEREQ = _descriptor.Descriptor(
  name='WebshellDisableReq',
  full_name='mower.WebshellDisableReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=201,
)


_WEBSHELLDISABLERSP = _descriptor.Descriptor(
  name='WebshellDisableRsp',
  full_name='mower.WebshellDisableRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='errror_code', full_name='mower.WebshellDisableRsp.errror_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='mower.WebshellDisableRsp.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WEBSHELLDISABLERSP_ERRORCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=333,
)

_WEBSHELLENABLERSP.fields_by_name['errror_code'].enum_type = _WEBSHELLENABLERSP_ERRORCODE
_WEBSHELLENABLERSP_ERRORCODE.containing_type = _WEBSHELLENABLERSP
_WEBSHELLDISABLERSP.fields_by_name['errror_code'].enum_type = _WEBSHELLDISABLERSP_ERRORCODE
_WEBSHELLDISABLERSP_ERRORCODE.containing_type = _WEBSHELLDISABLERSP
DESCRIPTOR.message_types_by_name['WebshellEnableReq'] = _WEBSHELLENABLEREQ
DESCRIPTOR.message_types_by_name['WebshellEnableRsp'] = _WEBSHELLENABLERSP
DESCRIPTOR.message_types_by_name['WebshellDisableReq'] = _WEBSHELLDISABLEREQ
DESCRIPTOR.message_types_by_name['WebshellDisableRsp'] = _WEBSHELLDISABLERSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WebshellEnableReq = _reflection.GeneratedProtocolMessageType('WebshellEnableReq', (_message.Message,), {
  'DESCRIPTOR' : _WEBSHELLENABLEREQ,
  '__module__' : 'webshell_agent_pb2'
  # @@protoc_insertion_point(class_scope:mower.WebshellEnableReq)
  })
_sym_db.RegisterMessage(WebshellEnableReq)

WebshellEnableRsp = _reflection.GeneratedProtocolMessageType('WebshellEnableRsp', (_message.Message,), {
  'DESCRIPTOR' : _WEBSHELLENABLERSP,
  '__module__' : 'webshell_agent_pb2'
  # @@protoc_insertion_point(class_scope:mower.WebshellEnableRsp)
  })
_sym_db.RegisterMessage(WebshellEnableRsp)

WebshellDisableReq = _reflection.GeneratedProtocolMessageType('WebshellDisableReq', (_message.Message,), {
  'DESCRIPTOR' : _WEBSHELLDISABLEREQ,
  '__module__' : 'webshell_agent_pb2'
  # @@protoc_insertion_point(class_scope:mower.WebshellDisableReq)
  })
_sym_db.RegisterMessage(WebshellDisableReq)

WebshellDisableRsp = _reflection.GeneratedProtocolMessageType('WebshellDisableRsp', (_message.Message,), {
  'DESCRIPTOR' : _WEBSHELLDISABLERSP,
  '__module__' : 'webshell_agent_pb2'
  # @@protoc_insertion_point(class_scope:mower.WebshellDisableRsp)
  })
_sym_db.RegisterMessage(WebshellDisableRsp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
