# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webshell_agent.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14webshell_agent.proto\x12\x05mower\"\x13\n\x11WebshellEnableReq\"\x7f\n\x11WebshellEnableRsp\x12\x37\n\x0b\x65rrror_code\x18\x01 \x01(\x0e\x32\".mower.WebshellEnableRsp.ErrorCode\x12\x0b\n\x03msg\x18\x02 \x01(\t\"$\n\tErrorCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\"\x14\n\x12WebshellDisableReq\"\x81\x01\n\x12WebshellDisableRsp\x12\x38\n\x0b\x65rrror_code\x18\x01 \x01(\x0e\x32#.mower.WebshellDisableRsp.ErrorCode\x12\x0b\n\x03msg\x18\x02 \x01(\t\"$\n\tErrorCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x42\x06Z\x04.;pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'webshell_agent_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004.;pb'
  _WEBSHELLENABLEREQ._serialized_start=31
  _WEBSHELLENABLEREQ._serialized_end=50
  _WEBSHELLENABLERSP._serialized_start=52
  _WEBSHELLENABLERSP._serialized_end=179
  _WEBSHELLENABLERSP_ERRORCODE._serialized_start=143
  _WEBSHELLENABLERSP_ERRORCODE._serialized_end=179
  _WEBSHELLDISABLEREQ._serialized_start=181
  _WEBSHELLDISABLEREQ._serialized_end=201
  _WEBSHELLDISABLERSP._serialized_start=204
  _WEBSHELLDISABLERSP._serialized_end=333
  _WEBSHELLDISABLERSP_ERRORCODE._serialized_start=143
  _WEBSHELLDISABLERSP_ERRORCODE._serialized_end=179
# @@protoc_insertion_point(module_scope)
