start_service_name: "start_capture" # Defines name suffix for std_srvs::Empty service which restarts suspended streaming
stop_service_name: "stop_capture"   # Defines name suffix for std_srvs::Empty service which suspends camera polling timer

video_device: /dev/video22           # Device driver's entrypoint
io_method: mmap                     # I/O method
                                    # - read - for devices supporting virtual filesystem or block I/O
                                    # - mmap - for devices with direct libusb memory mapping
                                    # - userptr - for userspace devices supporting userspace pointer exchange
pixel_format: mjpeg                 # Pixel format for Video4linux device (also selects decoder mode)
                                        # https://wiki.videolan.org/YUV#YUV_4:2:0_.28I420.2FJ420.2FYV12.29
                                        # - yuyv - YUV420
                                        # - yuv - synonym for yuyv
                                        # - uyvy - UVY240
                                        # - yuvmono10 - Monochrome 10-bit pseudo-YUV
                                        # - rgb24 - Linear 8-bit RGB
                                        # - bgr24 - OpenCV-compatible 8-bit BGR
                                        # - grey - Grayscale 8-bit monochrome
                                        # - yu12 - YU-reversed YUV420
                                        # - mjpeg - FFMPEG decoder, MotionJPEG, for compatible hardware
                                        # - h264 - FFMPEG decoder, H.264, for compatible hardware
color_format: yuv422p               # On-chip color representation mode for the input frame encoded by hardware
                                        # - yuv422p - YUV422 - default, compatible with most MJPEG hardware encoders
                                        # - yuv420p - YUV420 - mandatory for H.264 and H.265 hardware encoders
create_suspended: false             # Instructs the node whether to start streaming immediately after launch
                                    # or to wait until the start service will be triggered
full_ffmpeg_log: false              # Allows to suppress warning messages generated by libavcodec, cleans log
camera_name: rear_camera            # ROS internal name for the camera, used to generate camera_info message
camera_frame_id: rear_camera        # Frame ID used to generate coordinate transformations
camera_transport_suffix: image_raw  # Suffix used by image_transport to generate topic names
camera_info_url: "package://base_cameras/config/usb_cam_info.yaml"                 # URI for camera calibration data (likely a YML file obtained from camera_calibration)
image_width: 1920                    # Frame dimensions, should be supported by camera hardware
image_height: 1080
framerate: 30                       # Camera polling frequency, Hz (integer)

# Auxiliary camera parameters provided by libv4l2.
    # Names for these parameters are generated automatically according to the intrinsic control names exported by the
    # camera driver. The node queries camera's kernel controller module to determine the parameters that can be set up
    # via ROS. For these parameters the corresponding ROS parameters with identical names are generated under this
    # namespace.
    # See also the comprehensive node output describing parameter names and feasible values for them to be set up here.
    # It is also possible to have a list of the available control names using v4l2-ctl application from v4l2-util package:
    # v4l2-ctl --device=/dev/video<ID> -L
    #
    # V4L2_CID_EXPOSURE_AUTO_PRIORITY 是一个布尔类型的控制选项，当 V4L2_CID_EXPOSURE_AUTO 设置为 AUTO 或 APERTURE_PRIORITY 时，此控制选项决定设备是否可以动态调整帧率。
    # 具体作用：
    # 默认情况下 (0): 该选项被禁用，意味着帧率必须保持恒定不变。即使光线条件变化，摄像头也不会通过改变帧率来调节曝光。
    # 启用此选项 (1): 摄像头可以根据光线条件的变化动态调整帧率，以便优化曝光。例如，在光线不足的情况下，摄像头可能会降低帧率，以延长每帧的曝光时间，从而捕捉到更多的光线。
    # 
    # 典型场景：
    # 启用的情况: 如果需要在不同光线条件下自动获得最佳图像质量，可以启用此选项，这样摄像头可以根据需要调整帧率来提高图像亮度。
    # 禁用的情况: 如果对帧率有严格要求，比如需要稳定的视频流或时间同步的应用，则应禁用此选项，确保帧率始终保持一致。
intrinsic_controls:                 
    focus_auto: true
    exposure_auto_priority: true # 允许因自动曝光引发的帧率变化
    exposure_auto: 3 # 光圈优先
    white_balance_temperature_auto: true
    power_line_frequency: 1
    ignore: [
        brightness,
        contrast,
        saturation,
        gain,
        sharpness,
        backlight_compensation,
        white_balance_temperature,
        exposure_absolute,
        pan_absolute,
        tilt_absolute,
        focus_absolute,
        zoom_absolute
    ]                               # Use this list to enumerate the control names that should be delisted from the camera setup
                                    # NOTE: the ROS parameters for the V4L controls supported but listed here would be STILL
                                    # generated, but the values WILL NOT BE USED to set up the camera. To affect these controls
                                    # once you want to do that, their names should me REMOVED from this list!

