<?xml version="1.0"?>
<package format="3">
  <name>wit_imu_driver</name>
  <version>0.1.0</version>
  <description>WIT-Motion JY61P IMU driver for ROS 2 Humble</description>
  <maintainer email="michael@example.com">michael</maintainer>

  <license>Apache-2.0</license>

  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>rclpy</depend>
  <depend>tf2_ros</depend>
  <exec_depend>python3-serial</exec_depend>

  <buildtool_depend>ament_python</buildtool_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>