# Copyright 2026 ROS 2 port team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Nav2 navigation stack for the Airseekers Tron (ROS 2 Humble).

Starts controller_server, planner_server, behavior_server, bt_navigator,
velocity_smoother, collision_monitor (+ its plain-node helper collision_zone_gate) and
lifecycle_manager_navigation. With ``use_keepout:=true`` it also starts
costmap_filter_info_server under its own lifecycle manager.

``transit_controller:=mppi|rpp`` (default mppi) picks what the BT's FollowPath id runs
(launch/nav2_param_tools.py; rpp = the pre-2026-10-09 RPP transit, FollowPathRPP).

Expects (from launch/nav2.launch.py + the URDF): TF map -> odom -> base_link,
and /odometry/filtered. No map_server, no AMCL.

Velocity chain (all geometry_msgs/Twist, unstamped):
    controller_server  cmd_vel -> /cmd_vel_nav_raw
    velocity_smoother  /cmd_vel_nav_raw -> /cmd_vel_nav_smoothed
    collision_monitor  /cmd_vel_nav_smoothed -> /cmd_vel_nav   (twist_mux nav lane, 10)
    behavior_server    cmd_vel -> /cmd_vel_nav
Docking (/cmd_vel_docking), teleop, bumper and emergency lanes bypass the collision_monitor.
"""

import os
import sys
import tempfile

import yaml

from launch import LaunchDescription
from launch.actions import (DeclareLaunchArgument, GroupAction, LogInfo, OpaqueFunction,
                            SetLaunchConfiguration)
from launch.conditions import IfCondition
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from launch_ros.substitutions import FindPackageShare

LIFECYCLE_NODES = [
    "controller_server",
    "planner_server",
    "behavior_server",
    "bt_navigator",
    "velocity_smoother",
    "collision_monitor",   # after its input (velocity_smoother), as in nav2_bringup
]

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import nav2_param_tools  # noqa: E402


def _apply_transit_controller(context):
    """Rewrite params_file for transit_controller (and map a GUI transit_speed onto MPPI)."""
    mode = LaunchConfiguration("transit_controller").perform(context)
    base = LaunchConfiguration("params_file").perform(context)
    with open(base, encoding="utf-8") as f:
        doc = yaml.safe_load(f) or {}
    out = nav2_param_tools.apply_transit_controller(doc, mode)
    if out == doc:
        return [LogInfo(msg="transit_controller:=%s: FollowPath unchanged" % mode)]
    fd, path = tempfile.mkstemp(prefix="nav2_params_transit_", suffix=".yaml")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write("# generated by navigation.launch.py (transit_controller:=%s) from %s\n"
                % (mode, base))
        yaml.safe_dump(out, f, default_flow_style=False, sort_keys=False)
    return [SetLaunchConfiguration("params_file", path),
            LogInfo(msg="transit_controller:=%s: FollowPath params rewritten -> %s"
                        % (mode, path))]


def generate_launch_description() -> LaunchDescription:
    share = FindPackageShare("mower_navigation")
    params_file = LaunchConfiguration("params_file")
    autostart = ParameterValue(LaunchConfiguration("autostart"), value_type=bool)
    log_level = LaunchConfiguration("log_level")

    common = {
        "output": "screen",
        # Crash recovery (docs/crash_recovery.md): a crashed server is respawned by launch,
        # lifecycle_manager_navigation notices the broken bond (bond_timeout), resets the
        # stack and, with attempt_respawn_reconnection, re-configures + re-activates every
        # server once all of them are back (bond_respawn_max_duration).
        "respawn": True,
        "respawn_delay": 2.0,
        "arguments": ["--ros-args", "--log-level", log_level],
    }
    tf_remaps = [("/tf", "tf"), ("/tf_static", "tf_static")]

    args = [
        DeclareLaunchArgument(
            "params_file",
            default_value=PathJoinSubstitution([share, "config", "nav2_params.yaml"]),
            description="Full path to the Nav2 parameter file."),
        DeclareLaunchArgument(
            "use_keepout", default_value="false",
            description="Start costmap_filter_info_server (keepout filter info on "
                        "/costmap_filter_info, mask /keepout_mask). The global "
                        "costmap's keepout_filter is configured either way."),
        DeclareLaunchArgument(
            "autostart", default_value="true",
            description="Configure + activate the lifecycle nodes automatically."),
        DeclareLaunchArgument("log_level", default_value="info"),
        DeclareLaunchArgument(
            "transit_controller", default_value="mppi",
            description="What controller_id FollowPath (BT transits, docking approach) "
                        "runs: mppi (nav2_mppi_controller, default since 2026-10-09) or "
                        "rpp (the previous RegulatedPurePursuit, FollowPathRPP)."),
    ]

    nodes = [
        Node(
            package="nav2_controller", executable="controller_server",
            name="controller_server",
            parameters=[params_file],
            remappings=tf_remaps + [
                ("cmd_vel", "/cmd_vel_nav_raw"),
                ("odom", "/odometry/filtered"),
            ],
            **common),
        Node(
            package="nav2_planner", executable="planner_server",
            name="planner_server",
            parameters=[params_file],
            remappings=tf_remaps,
            **common),
        Node(
            package="nav2_behaviors", executable="behavior_server",
            name="behavior_server",
            parameters=[params_file],
            remappings=tf_remaps + [("cmd_vel", "/cmd_vel_nav")],
            **common),
        Node(
            package="nav2_bt_navigator", executable="bt_navigator",
            name="bt_navigator",
            parameters=[params_file, {
                "default_nav_to_pose_bt_xml": PathJoinSubstitution(
                    [share, "behavior_trees",
                     "navigate_to_pose_w_replanning_and_recovery.xml"]),
                "default_nav_through_poses_bt_xml": PathJoinSubstitution(
                    [share, "behavior_trees",
                     "navigate_through_poses_w_replanning_and_recovery.xml"]),
            }],
            remappings=tf_remaps,
            **common),
        Node(
            package="nav2_velocity_smoother", executable="velocity_smoother",
            name="velocity_smoother",
            parameters=[params_file],
            remappings=tf_remaps + [
                ("cmd_vel", "/cmd_vel_nav_raw"),
                ("cmd_vel_smoothed", "/cmd_vel_nav_smoothed"),
            ],
            **common),
        # Topics come from its params (cmd_vel_in_topic / cmd_vel_out_topic).
        Node(
            package="nav2_collision_monitor", executable="collision_monitor",
            name="collision_monitor",
            parameters=[params_file],
            remappings=tf_remaps,
            **common),
        # Plain node (not lifecycle): stop/slowdown zones forward-only (see its docstring).
        Node(
            package="mower_navigation", executable="collision_zone_gate.py",
            name="collision_zone_gate",
            parameters=[params_file],
            **common),
        Node(
            package="nav2_lifecycle_manager", executable="lifecycle_manager",
            name="lifecycle_manager_navigation",
            parameters=[params_file,
                        {"autostart": autostart, "node_names": LIFECYCLE_NODES,
                         "attempt_respawn_reconnection": True}],
            **common),
    ]

    keepout = GroupAction(
        condition=IfCondition(LaunchConfiguration("use_keepout")),
        actions=[
            Node(
                package="nav2_map_server", executable="costmap_filter_info_server",
                name="costmap_filter_info_server",
                parameters=[params_file],
                **common),
            Node(
                package="nav2_lifecycle_manager", executable="lifecycle_manager",
                name="lifecycle_manager_costmap_filters",
                parameters=[params_file, {
                    "autostart": autostart,
                    "node_names": ["costmap_filter_info_server"],
                    "attempt_respawn_reconnection": True,
                }],
                **common),
        ])

    return LaunchDescription(args + [OpaqueFunction(function=_apply_transit_controller)]
                             + nodes + [keepout])
